/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session-check endpoint backing the SPA's AuthGate-equivalent hook.
         * @description Same response shape as the public API's `GET /api/v1/me`, deliberately — one response shape for "who am I," regardless of which surface asked.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every agent's non-revoked API keys (I21).
         * @description Every `role='agent'` user's non-revoked keys (`revoked_at IS NULL`), not just the session owner's own — the session owner never holds a key at all (`role='owner'` can't be issued one, I2), so scoping this to the caller would always return empty, which was milestone-2/3's actual bug. Regardless of expiry: an expired-but-unrevoked key still shows up so the owner can see it needs rotating. Each row carries the owning agent's `handle` (never null — only rows a real users JOIN produced ever reach this response), so the owner can tell whose key is whose before revoking one.
         */
        get: operations["listKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke any agent's API key by id (I21).
         * @description Sets `revoked_at`. Not scoped to a "caller's own" key — there is no such thing on this owner-only surface (I2) — any agent's key id may be revoked, session-gated only. An unknown id is `404 not_found`, the same "absence, not permission" shape every other owner-scoped-by-nothing-left-to-scope lookup on this surface uses. No `POST /keys` and no rotate endpoint anywhere on this surface, deliberately — a raw key can't be returned safely over an HTTP response, so issuance/rotation stay CLI-only (`cmd/issue-key`) regardless of which surface is asking.
         */
        delete: operations["revokeKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every active user, either role.
         * @description Mirrors my-task's own `user.ts` router (`list` only, `WHERE active = true ORDER BY handle`, "humans and agents in one list"). List only: no create, no update, no delete — my-task's router has none of those either, and there is no reason to exceed it. Owner-session only, same tier as every other endpoint on this surface; an agent has no business enumerating users (there is no equivalent on `openapi.yaml`'s public API at all).
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage totals and one-dimension breakdown for a time window.
         * @description story-1/ticket-14: the console's own read surface over `usage_events` (`_rules/../story-1/_contract/contract.md`'s "API surface" section — wire field names below are copied verbatim from that contract, including its `snake_case` `group_by`/`reporting_installs`, which deliberately breaks from this surface's own camelCase convention elsewhere; not "corrected" here since the contract is this ticket's literal input, not something to reopen). `window` selects the [start, now) range (`today`/`week`/`month` are calendar-anchored at UTC midnight/Monday/1st; `5h`/`24h` are rolling); `group_by` picks which dimension the `breakdown` array is keyed by. `totals.tokens` sums all four raw token counters per event (input + output + cache_read + cache_creation) — a single display number, distinct from ticket 9's "never summed into each other" rule about the *stored* per-field columns, which this endpoint only ever reads, never rewrites. `reporting_installs` is the count of distinct `machine` values with at least one event inside the selected window (not lifetime) — the goal's partial-view caveat, scoped to what the rest of this response actually covers.
         *
         *     `lifetime` was originally a sixth value, additive to the contract's own fixed five (`_contract/contract.md`'s API surface section originally named exactly `5h|24h|today|week|month`) — flagged as a build-time decision in ticket 14's own report: the ticket's own mockup spec names a "lifetime cost" summary tile, which none of the five original windows could answer (each has a bounded start). `lifetime` covers every event ever ingested up to now, with no left bound.
         *     story-1/ticket-20 adds `year` (calendar-anchored at Jan 1 00:00 UTC of the current year, matching `today`/`week`/`month`'s own calendar-boundary convention — not a rolling 365-day window), and reopens ticket 14's "`lifetime` is query-string-additive only, never in the fixed table" call: both `year` and `lifetime` are now real, selectable tabs that also drive `GET /usage/windows`' own fixed table (now seven rows, see that operation below), not just this endpoint's own `window` query parameter.
         */
        get: operations["getUsageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Turns/tokens/cost for each of the fixed 5h/24h/today/week/month/year/lifetime windows.
         * @description story-1/ticket-14: backs the console's time-window table — one row per fixed window, each computed the same way `getUsageSummary`'s own `window` parameter computes its range, with no `group_by` (each row is this service's whole reporting surface's totals for that window, not split by dimension).
         *     story-1/ticket-20: grows from five rows to seven — `year` and `lifetime` are now real, selectable tabs (reopening ticket 14's "lifetime is tab-only-tile, never a tab" call), so both belong in this fixed table too for consistency between what's clickable and what's listed.
         */
        get: operations["getUsageWindows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            handle: string;
            role: string;
            active: boolean;
        };
        ApiKey: {
            id: string;
            prefix: string;
            /** @description milestone-4 fix-round (handle-exposure): the owning agent's handle — my-task's own api-key-settings.tsx shows `{k.handle}` on every row and its revoke dialog names the agent by handle ("Revoke {handle}'s key?"); this endpoint (GET /api/bff/keys) already JOINs users for every row it returns (I21 — every key here belongs to a role='agent' user), so this is always present, never null. */
            handle: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ApiKeyList: {
            keys: components["schemas"]["ApiKey"][];
        };
        /** @description One row of GET /users. Every active user, either role — `role` rides along so a client could group/label by it. */
        User: {
            id: string;
            handle: string;
            /** @enum {string} */
            role: "owner" | "agent";
            /** @description Always `true` on every row this endpoint returns (`WHERE active = true` server-side) — present on the wire anyway so this schema doesn't silently drift from `Me`'s own `{handle, role, active}` shape if that ever changes. */
            active: boolean;
        };
        UserList: {
            users: components["schemas"]["User"][];
        };
        UsageTotals: {
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
            /** Format: int64 */
            turns: number;
        };
        UsageBreakdownRow: {
            /** @description The dimension value to display: an actor name, a canonicalized path, or — group_by=machine, story-1/ticket-18 — the reporting machine's `hostname` (joined from `machines` on `usage_events.machine` = `machines.install_id`), not the raw `install_id`, falling back to the raw `install_id` itself if a machine has events but no corresponding `machines` row. group_by=path (story-2/ticket-7) is machine-prefixed: `<hostname>:<path>` once substituted, falling back to `<install_id>:<path>` the same way. Display shortening beyond this substitution (contract's "Console display rules", `path` basename/collision handling) is still the SPA's own job, not this endpoint's. */
            key: string;
            /** @description Present only when `key` has been substituted for a friendlier display value: group_by=machine (`key` becomes the hostname, raw_key the machine's `install_id`), or — story-2/ticket-7 — group_by=path (`key` becomes `<hostname>:<path>`, raw_key the ground-truth `<install_id>:<path>`). Carries the raw value so the console can still surface it, e.g. via a tooltip (contract's "machine label"/"Cross-machine path identity" rules — same "shortened label, full value still reachable" pattern in both cases). Absent for every other group_by, and for the no-machines-row fallback case, since `key` is already the raw value there. */
            raw_key?: string;
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
            /** Format: int64 */
            turns: number;
        };
        UsageSummary: {
            totals: components["schemas"]["UsageTotals"];
            /** @description Every distinct key for the requested group_by within the window, cost descending. */
            breakdown: components["schemas"]["UsageBreakdownRow"][];
            /**
             * Format: int64
             * @description Distinct `machine`s with at least one event inside the selected window — not lifetime.
             */
            reporting_installs: number;
        };
        UsageWindowRow: {
            /** @enum {string} */
            window: "5h" | "24h" | "today" | "week" | "month" | "year" | "lifetime";
            /** Format: int64 */
            turns: number;
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
        };
        UsageWindows: {
            windows: components["schemas"]["UsageWindowRow"][];
        };
        Error: {
            error: {
                code: string;
                message: string;
                hint?: string;
            };
        };
    };
    responses: {
        /** @description The request violates a request-shape or validation rule. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, expired, or wrong-role session cookie — same shape regardless of which check failed (I5). A behavior change from this package's own HTML `GET /` view: this JSON surface always answers 401, never a redirect (a `fetch` call can't follow a redirect the way a browser navigation does — the SPA's own AuthGate-equivalent hook is what turns a 401 into a redirect, client-side). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown id, or an id that exists but isn't the caller's (I3 — absence, not permission). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in owner. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every agent's non-revoked keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every active user, ordered by handle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUsageSummary: {
        parameters: {
            query: {
                window: "5h" | "24h" | "today" | "week" | "month" | "year" | "lifetime";
                group_by: "actor" | "path" | "machine";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Totals, a breakdown by the requested dimension, and the window-scoped reporting-install count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getUsageWindows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per fixed window, in 5h, 24h, today, week, month, year, lifetime order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageWindows"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
