/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session-check endpoint backing the SPA's AuthGate-equivalent hook.
         * @description Same response shape as the public API's `GET /api/v1/me`, deliberately — one response shape for "who am I," regardless of which surface asked.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every agent's non-revoked API keys (I21).
         * @description Every `role='agent'` user's non-revoked keys (`revoked_at IS NULL`), not just the session owner's own — the session owner never holds a key at all (`role='owner'` can't be issued one, I2), so scoping this to the caller would always return empty, which was milestone-2/3's actual bug. Regardless of expiry: an expired-but-unrevoked key still shows up so the owner can see it needs rotating. Each row carries the owning agent's `handle` (never null — only rows a real users JOIN produced ever reach this response), so the owner can tell whose key is whose before revoking one.
         */
        get: operations["listKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke any agent's API key by id (I21).
         * @description Sets `revoked_at`. Not scoped to a "caller's own" key — there is no such thing on this owner-only surface (I2) — any agent's key id may be revoked, session-gated only. An unknown id is `404 not_found`, the same "absence, not permission" shape every other owner-scoped-by-nothing-left-to-scope lookup on this surface uses. No `POST /keys` and no rotate endpoint anywhere on this surface, deliberately — a raw key can't be returned safely over an HTTP response, so issuance/rotation stay CLI-only (`cmd/issue-key`) regardless of which surface is asking.
         */
        delete: operations["revokeKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every active user, either role.
         * @description Mirrors my-task's own `user.ts` router (`list` only, `WHERE active = true ORDER BY handle`, "humans and agents in one list"). List only: no create, no update, no delete — my-task's router has none of those either, and there is no reason to exceed it. Owner-session only, same tier as every other endpoint on this surface; an agent has no business enumerating users (there is no equivalent on `openapi.yaml`'s public API at all).
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage totals and one-dimension breakdown for a time window.
         * @description story-1/ticket-14: the console's own read surface over `usage_events` (`_rules/../story-1/_contract/contract.md`'s "API surface" section — wire field names below are copied verbatim from that contract, including its `snake_case` `group_by`/`reporting_installs`, which deliberately breaks from this surface's own camelCase convention elsewhere; not "corrected" here since the contract is this ticket's literal input, not something to reopen). `window` selects the [start, now) range (`today`/`week`/`month` are calendar-anchored at UTC midnight/Monday/1st; `5h`/`24h` are rolling); `group_by` picks which dimension the `breakdown` array is keyed by. `totals.tokens` sums all four raw token counters per event (input + output + cache_read + cache_creation) — a single display number, distinct from ticket 9's "never summed into each other" rule about the *stored* per-field columns, which this endpoint only ever reads, never rewrites. `reporting_installs` is the count of distinct `machine` values with at least one event inside the selected window (not lifetime) — the goal's partial-view caveat, scoped to what the rest of this response actually covers.
         *
         *     `lifetime` was originally a sixth value, additive to the contract's own fixed five (`_contract/contract.md`'s API surface section originally named exactly `5h|24h|today|week|month`) — flagged as a build-time decision in ticket 14's own report: the ticket's own mockup spec names a "lifetime cost" summary tile, which none of the five original windows could answer (each has a bounded start). `lifetime` covers every event ever ingested up to now, with no left bound.
         *     story-1/ticket-20 adds `year` (calendar-anchored at Jan 1 00:00 UTC of the current year, matching `today`/`week`/`month`'s own calendar-boundary convention — not a rolling 365-day window), and reopens ticket 14's "`lifetime` is query-string-additive only, never in the fixed table" call: both `year` and `lifetime` are now real, selectable tabs that also drive `GET /usage/windows`' own fixed table (now seven rows, see that operation below), not just this endpoint's own `window` query parameter.
         */
        get: operations["getUsageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Turns/tokens/cost for each of the fixed 5h/24h/today/week/month/year/lifetime windows.
         * @description story-1/ticket-14: backs the console's time-window table — one row per fixed window, each computed the same way `getUsageSummary`'s own `window` parameter computes its range, with no `group_by` (each row is this service's whole reporting surface's totals for that window, not split by dimension).
         *     story-1/ticket-20: grows from five rows to seven — `year` and `lifetime` are now real, selectable tabs (reopening ticket 14's "lifetime is tab-only-tile, never a tab" call), so both belong in this fixed table too for consistency between what's clickable and what's listed.
         *     story-2/ticket-10: gains the same two optional `machine`/ `scan_root` filters `getUsageSummary` already has, so the fixed table also respects an active console filter (story-1 shipped this endpoint with zero params) -- see that operation's own `machine`/`scan_root` parameter docs for the exact semantics, identical here.
         */
        get: operations["getUsageWindows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/scan-roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every registered scan root across every reporting install.
         * @description story-2/ticket-9: no parameters — exists purely to populate the console's future scan-root filter dropdown (ticket 11), since there is no `group_by=scan_root` breakdown panel this story's scope adds to derive the list from otherwise. Each row joins `scan_roots` to `machines` on `install_id` for the hostname, the same join style `getUsageSummary`'s own hostname substitution already uses (read via a repo method, not a SQL JOIN, per that same precedent) — `hostname` falls back to the raw `install_id` itself if a scan root's install_id has no corresponding `machines` row (shouldn't normally happen given both are upserted from the same ingestion batch, but the same "never a blank label" rule `getUsageSummary`'s own `machine`/`path` group_by fallback already sets applies here too).
         */
        get: operations["getUsageScanRoots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every machine's lifetime summary, sorted by last reported descending.
         * @description story-3/ticket-1: the Machines page's own read surface (goal's point 3, a fleet-overview list — deliberately lifetime-scoped, no window/group_by parameter at all, unlike `getUsageSummary` above). Backs both the overview table and the detail page's own identity/stats block (contract's API surface: the detail page finds its one row by `install_id` from this same response rather than a second, single-machine endpoint). Pre-sorted `last_seen_at` descending, matching `ListMachineSummaries`'s own `ORDER BY` — no client-side re-sort needed.
         */
        get: operations["getMachines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            handle: string;
            role: string;
            active: boolean;
        };
        ApiKey: {
            id: string;
            prefix: string;
            /** @description milestone-4 fix-round (handle-exposure): the owning agent's handle — my-task's own api-key-settings.tsx shows `{k.handle}` on every row and its revoke dialog names the agent by handle ("Revoke {handle}'s key?"); this endpoint (GET /api/bff/keys) already JOINs users for every row it returns (I21 — every key here belongs to a role='agent' user), so this is always present, never null. */
            handle: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ApiKeyList: {
            keys: components["schemas"]["ApiKey"][];
        };
        /** @description One row of GET /users. Every active user, either role — `role` rides along so a client could group/label by it. */
        User: {
            id: string;
            handle: string;
            /** @enum {string} */
            role: "owner" | "agent";
            /** @description Always `true` on every row this endpoint returns (`WHERE active = true` server-side) — present on the wire anyway so this schema doesn't silently drift from `Me`'s own `{handle, role, active}` shape if that ever changes. */
            active: boolean;
        };
        UserList: {
            users: components["schemas"]["User"][];
        };
        UsageTotals: {
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
            /** Format: int64 */
            turns: number;
        };
        UsageBreakdownRow: {
            /** @description The dimension value to display: an actor name, a canonicalized path, or — group_by=machine, story-1/ticket-18 — the reporting machine's `hostname` (joined from `machines` on `usage_events.machine` = `machines.install_id`), not the raw `install_id`, falling back to the raw `install_id` itself if a machine has events but no corresponding `machines` row. group_by=path (story-2/ticket-7) is machine-prefixed: `<hostname>:<path>` once substituted, falling back to `<install_id>:<path>` the same way. Display shortening beyond this substitution (contract's "Console display rules", `path` basename/collision handling) is still the SPA's own job, not this endpoint's. */
            key: string;
            /** @description Present only when `key` has been substituted for a friendlier display value: group_by=machine (`key` becomes the hostname, raw_key the machine's `install_id`), or — story-2/ticket-7 — group_by=path (`key` becomes `<hostname>:<path>`, raw_key the ground-truth `<install_id>:<path>`). Carries the raw value so the console can still surface it, e.g. via a tooltip (contract's "machine label"/"Cross-machine path identity" rules — same "shortened label, full value still reachable" pattern in both cases). Absent for every other group_by, and for the no-machines-row fallback case, since `key` is already the raw value there. */
            raw_key?: string;
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
            /** Format: int64 */
            turns: number;
        };
        UsageSummary: {
            totals: components["schemas"]["UsageTotals"];
            /** @description Every distinct key for the requested group_by within the window, cost descending. */
            breakdown: components["schemas"]["UsageBreakdownRow"][];
            /**
             * Format: int64
             * @description Distinct `machine`s with at least one event inside the selected window — not lifetime.
             */
            reporting_installs: number;
        };
        UsageWindowRow: {
            /** @enum {string} */
            window: "5h" | "24h" | "today" | "week" | "month" | "year" | "lifetime";
            /** Format: int64 */
            turns: number;
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
        };
        UsageWindows: {
            windows: components["schemas"]["UsageWindowRow"][];
        };
        /** @description story-2/ticket-9: one row of GET /usage/scan-roots. Field names are snake_case verbatim from the contract's own API surface section, matching the rest of this usage domain's own break from this spec's otherwise-camelCase convention (see getUsageSummary's own doc comment for why). story-3/ticket-2 adds `source_type`, additive to ticket-9's own shape (already a real column on `scan_roots` — story-2/ticket-8 — just never selected/exposed here since ticket-9 only needed this endpoint for the filter dropdown, which doesn't display it); no existing consumer needs to change. */
        UsageScanRoot: {
            /** @description The reporting install's raw install_id — always present, even when hostname had to fall back to it. */
            install_id: string;
            /** @description machines.hostname for this row's install_id, falling back to the raw install_id itself if no corresponding machines row exists (never a blank label). */
            hostname: string;
            /** @description The raw scan-root path, as configured in the collector's own scan_paths. */
            scan_root_path: string;
            /** @description The operator-assigned label for this scan root (per-install, no shared/global naming registry across machines). */
            name: string;
            /** @description A declared category at config time (defaults to "claude_code" if the collector's own config omitted it) — same value ingested via the batch's own `scan_roots[]. source_type` (openapi.yaml's `ScanRootInput`), read back verbatim here (story-3/ticket-2). */
            source_type: string;
        };
        UsageScanRootList: {
            /** @description Every registered scan root across every reporting install. */
            scan_roots: components["schemas"]["UsageScanRoot"][];
        };
        /** @description story-3/ticket-1: one row of GET /machines. Named Machine, not MachineSummary, deliberately distinct from the domain-layer usage.MachineSummary it's generated alongside (internal/domain/ usage/repo.go) — same "distinct name per layer" convention ScanRootRecord/ScanRootWithHostname/UsageScanRoot already establish, so a reader/grep is never left guessing which package's type a bare "MachineSummary" means. Field names are snake_case verbatim from the contract's own API surface section, same break from this spec's otherwise-camelCase convention as UsageScanRoot above (this usage domain's own established exception — see getUsageSummary's own doc comment for why). */
        Machine: {
            /** @description The reporting install's raw install_id — always present, reachable via a tooltip on the console (goal's point 3). */
            install_id: string;
            /** @description machines.hostname for this row's install_id — always present (machines.hostname is NOT NULL; no fallback needed the way UsageScanRoot's own hostname sometimes does). */
            hostname: string;
            /**
             * Format: date-time
             * @description machines.last_seen_at verbatim — stamped by the server's own clock at ingestion time, deliberately NOT MAX(usage_events.created_at) (contract's Data model: "Last reported" answers "is this machine's collector still alive," a different question from "when did a person last actually use it").
             */
            last_seen_at: string;
            /**
             * Format: double
             * @description SUM(usage_events.cost) across every event this machine has ever reported, 0 (not null) when it has none.
             */
            lifetime_cost: number;
            /**
             * Format: int64
             * @description SUM of all four token columns (input + output + cache_read + cache_creation) across every event this machine has ever reported, 0 (not null) when it has none.
             */
            lifetime_tokens: number;
            /**
             * Format: int64
             * @description COUNT(DISTINCT usage_events.path) this machine has reported — "Collected Paths" on the console, a plain count, not an inference (goal's point 3).
             */
            collected_paths: number;
            /**
             * Format: int64
             * @description COUNT(DISTINCT usage_events.actor) this machine has reported — "Collected Actors" on the console, same "plain count" naming as collected_paths.
             */
            collected_actors: number;
        };
        MachineList: {
            /** @description Every machine's lifetime summary, sorted last_seen_at descending. */
            machines: components["schemas"]["Machine"][];
        };
        Error: {
            error: {
                code: string;
                message: string;
                hint?: string;
            };
        };
    };
    responses: {
        /** @description The request violates a request-shape or validation rule. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, expired, or wrong-role session cookie — same shape regardless of which check failed (I5). A behavior change from this package's own HTML `GET /` view: this JSON surface always answers 401, never a redirect (a `fetch` call can't follow a redirect the way a browser navigation does — the SPA's own AuthGate-equivalent hook is what turns a 401 into a redirect, client-side). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown id, or an id that exists but isn't the caller's (I3 — absence, not permission). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in owner. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every agent's non-revoked keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every active user, ordered by handle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUsageSummary: {
        parameters: {
            query: {
                window: "5h" | "24h" | "today" | "week" | "month" | "year" | "lifetime";
                group_by: "actor" | "path" | "machine";
                /** @description story-2/ticket-10: optional install_id filter. When set, scopes `totals`/`breakdown`/`reporting_installs` to only events reported by this machine -- not just one panel's own dimension (contract's Console filters section: global, not per-panel). AND-composed with `window` and with `scan_root` when both are set. Absent means no machine constraint. */
                machine?: string;
                /** @description story-2/ticket-10: optional composite `<install_id>:<scan_root_path>` filter -- same machine-prefix convention as `group_by=path`'s own cross-machine fix (ticket 7), for the identical reason: a bare scan-root path/name is ambiguous across machines since naming is per-install (contract's Data model). AND-composed with `window` and with `machine` when both are set. An invalid shape, or a well-formed but non-existent `install_id:scan_root_path` pair, yields an empty/zero result -- not a 400 -- mirroring this API's existing "no matching data" tolerance versus a malformed request. */
                scan_root?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Totals, a breakdown by the requested dimension, and the window-scoped reporting-install count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getUsageWindows: {
        parameters: {
            query?: {
                /** @description story-2/ticket-10 -- same optional install_id filter as getUsageSummary's own `machine` parameter. */
                machine?: string;
                /** @description story-2/ticket-10 -- same optional `<install_id>:<scan_root_path>` filter as getUsageSummary's own `scan_root` parameter. */
                scan_root?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per fixed window, in 5h, 24h, today, week, month, year, lifetime order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageWindows"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUsageScanRoots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every registered scan root, across every reporting install. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageScanRootList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMachines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every machine's lifetime summary, most recently reported first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
