/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session-check endpoint backing the SPA's AuthGate-equivalent hook.
         * @description Same response shape as the public API's `GET /api/v1/me`, deliberately — one response shape for "who am I," regardless of which surface asked.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every todo.
         * @description milestone-4: todos are a shared collection (`_rules/_contract/ DATA_MODEL.md`/`GOAL.md`'s Ownership model decision) — I3 no longer applies to this domain, on either surface. Returns every todo, created_at descending, unpaginated — same shape as `_rules/_contract/API.md`'s `GET /api/v1/todos`, not just the session owner's own.
         */
        get: operations["listTodos"];
        put?: never;
        /**
         * Create a todo, attributed to the caller.
         * @description `createdBy` is always the resolved session owner — never accepted from the body (I1, same rule as the public API, different auth mechanism) — but is attribution only, never access-scoping (GOAL.md). `status` always starts `open`. The `created` event this produces is never client-specifiable as a distinct write (I16) — it only ever happens as this endpoint's own side effect. `clientRequestId` makes this idempotent the same way `POST .../events` is (I19). Calls `internal/domain/todo.Service.CreateTodo` directly — the same service instance and method the public API's handler calls (`_rules/_standard/ARCHITECTURE.md`'s shared-service-layer rule).
         */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a todo by id.
         * @description milestone-4: every authenticated actor may read every todo (I3 no longer applies to this domain) — an unknown id is `not_found`, there is no "wrong owner" case left to produce it.
         */
        get: operations["getTodo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename a todo.
         * @description milestone-4: the only field this endpoint still writes is `title` — `status`/`assigneeId`/`priority`/`dueDate` changes route through `POST .../events` instead (`status_changed`/ `assigned`/`field_changed`), the single write path (I15/I18) those fields' permission/audit requirements actually need. `done` is gone entirely (replaced by `status`) — sending it is a `validation_error` (`hint: "done"`), not silently accepted and ignored. Internally still funnels through the same single write path as every other mutation (a `field_changed` event), hence `clientRequestId` (I19).
         */
        patch: operations["updateTodo"];
        trace?: never;
    };
    "/todos/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * This todo's own timeline.
         * @description Oldest first — same shape and ordering as `_rules/_contract/ API.md`'s `GET /api/v1/todos/{id}/events`. This todo's own timeline only; the cross-todo feed is `GET /api/bff/activity`, a separate endpoint (milestone-4/task-5).
         */
        get: operations["listTodoEvents"];
        put?: never;
        /**
         * Append an event to this todo's timeline (I15's single write path).
         * @description One body shape per `type` — `commented` (`body`), `status_changed` (`to`), `assigned` (`to`, or `null` to unassign), `field_changed` (`field`, `to`) — `_contract/API.md`. `type: "created"` is rejected (`validation_error`): a `created` event only ever happens as `POST /todos`'s own side effect, never as a direct client-specifiable write (I16) — the same rejection applies to any other value this endpoint doesn't recognise, `created` included, not a special case. **`status: closed` succeeds on this surface** (I18 — this is the owner's own surface; contrast with the public API, where a Bearer-authenticated agent caller is rejected as `unauthorized` for the same write). Idempotent on `clientRequestId` (I19): a repeated id returns the original event and creates nothing.
         */
        post: operations["createTodoEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The cross-todo activity feed — every event, across every todo, newest first.
         * @description `_contract/API.md`'s `GET /api/bff/activity`: a cursor over `todo_events` across every todo, newest first, joined to `todos` (title) and `users` (actor handle/role, so the caller can mark human vs agent). Owner-session only — mirrors my-task's `activity.list` (`~/gits/my-task/src/server/api/routers/ activity.ts`), adapted from tRPC's `{limit, cursor: {createdAtMs, id}}` input shape to this surface's plain-JSON query-string convention: `limit` (default 30, same as my-task's own default; 1-100 inclusive) plus `cursorCreatedAtMs`/`cursorId`, which must be supplied together or not at all (a lone one of the pair is a malformed cursor, `validation_error`). `nextCursor` in the response echoes the exact field names (`cursorCreatedAtMs`/`cursorId` on the way in, `createdAtMs`/`id` on the way out) so a client can round-trip it verbatim into the next page's query string. `nextCursor: null` means exhausted — mirrors `TaskQueryService.listActivity`'s own `hasMore` check (fetch `limit + 1` rows, an extra row present means there's a next page).
         */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every agent's non-revoked API keys (I21).
         * @description Every `role='agent'` user's non-revoked keys (`revoked_at IS NULL`), not just the session owner's own — the session owner never holds a key at all (`role='owner'` can't be issued one, I2), so scoping this to the caller would always return empty, which was milestone-2/3's actual bug. Regardless of expiry: an expired-but-unrevoked key still shows up so the owner can see it needs rotating. Each row carries the owning agent's `handle` (never null — only rows a real users JOIN produced ever reach this response), so the owner can tell whose key is whose before revoking one.
         */
        get: operations["listKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke any agent's API key by id (I21).
         * @description Sets `revoked_at`. Not scoped to a "caller's own" key — there is no such thing on this owner-only surface (I2) — any agent's key id may be revoked, session-gated only. An unknown id is `404 not_found`, the same "absence, not permission" shape every other owner-scoped-by-nothing-left-to-scope lookup on this surface uses. No `POST /keys` and no rotate endpoint anywhere on this surface, deliberately — a raw key can't be returned safely over an HTTP response, so issuance/rotation stay CLI-only (`cmd/issue-key`) regardless of which surface is asking.
         */
        delete: operations["revokeKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every active user, either role (the assignee picker's data source).
         * @description มายด์'s ask: "the assignee form in /todos/:id [should be] a drop[down] of the assignee, not freeform text." A dropdown needs a list of assignable users — this endpoint, mirroring my-task's own `user.ts` router (`list` only, `WHERE active = true ORDER BY handle`, "humans and agents in one list"). List only: no create, no update, no delete — my-task's router has none of those either, and there is no reason to exceed it. Owner-session only, same tier as every other endpoint on this surface; an agent has no business enumerating users (there is no equivalent on `openapi.yaml`'s public API at all). Returns `id` (what `Todo.assigneeId`/an `assigned` event's `to` actually writes back) alongside `handle` (what a picker displays) so a client never needs a second lookup between choosing a name and submitting the write.
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage totals and one-dimension breakdown for a time window.
         * @description story-1/ticket-14: the console's own read surface over `usage_events` (`_rules/../story-1/_contract/contract.md`'s "API surface" section — wire field names below are copied verbatim from that contract, including its `snake_case` `group_by`/`reporting_installs`, which deliberately breaks from this surface's own camelCase convention elsewhere; not "corrected" here since the contract is this ticket's literal input, not something to reopen). `window` selects the [start, now) range (`today`/`week`/`month` are calendar-anchored at UTC midnight/Monday/1st; `5h`/`24h` are rolling); `group_by` picks which dimension the `breakdown` array is keyed by. `totals.tokens` sums all four raw token counters per event (input + output + cache_read + cache_creation) — a single display number, distinct from ticket 9's "never summed into each other" rule about the *stored* per-field columns, which this endpoint only ever reads, never rewrites. `reporting_installs` is the count of distinct `machine` values with at least one event inside the selected window (not lifetime) — the goal's partial-view caveat, scoped to what the rest of this response actually covers.
         *
         *     `lifetime` is a sixth value, additive to the contract's own fixed five (`_contract/contract.md`'s API surface section names exactly `5h|24h|today|week|month`) — flagged as a build-time decision in ticket 14's own report, not silently added: the ticket's own mockup spec names a "lifetime cost" summary tile, which none of the five contract windows can answer (each has a bounded start). Query-string-additive only — `GET /usage/windows`' own fixed table is untouched, still exactly those five, in that order. `lifetime` covers every event ever ingested up to now, with no left bound.
         */
        get: operations["getUsageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Turns/tokens/cost for each of the fixed 5h/24h/today/week/month windows.
         * @description story-1/ticket-14: backs the console's time-window table — one row per fixed window, each computed the same way `getUsageSummary`'s own `window` parameter computes its range, with no `group_by` (each row is this service's whole reporting surface's totals for that window, not split by dimension).
         */
        get: operations["getUsageWindows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            handle: string;
            role: string;
            active: boolean;
        };
        Todo: {
            id: string;
            title: string;
            /**
             * @description milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
             * @enum {string}
             */
            status: "open" | "in_progress" | "done" | "closed";
            /** @description References a user (any role). */
            assigneeId: string | null;
            /** @description milestone-4 fix-round (handle-exposure): assigneeId's owning user's handle, for display — null exactly when assigneeId is null. my-task's own task list/detail views show a plain handle (`~/gits/my-task/src/server/modules/task/task.queries.ts`'s `assigneeHandle` LEFT JOIN, `t.assignee`/`detail.assignee` on the wire), never a bare id, and task-7's report found this repo's own Todo had no equivalent. Additive: assigneeId is unchanged, still what a caller writes back (CreateTodoRequest.assigneeId, CreateTodoEventRequest's `to` for an `assigned` event) — this is display-only, openapi.yaml's own Todo carries the identical field for the same reason (my-task's agent-facing REST shows it too, not just the owner UI). */
            assigneeHandle: string | null;
            /** @enum {string|null} */
            priority: "low" | "medium" | "high" | "urgent" | null;
            /** Format: date-time */
            dueDate: string | null;
            /** @description milestone-4: replaces `ownerId` — attribution only, never access-scoping (GOAL.md). */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TodoList: {
            todos: components["schemas"]["Todo"][];
        };
        TodoEvent: {
            id: string;
            todoId: string;
            /** Format: int64 */
            seq: number;
            actorId: string;
            /** @description milestone-4 fix-round (handle-exposure): the same `{handle, role}` shape `ActivityItem.actor` already carries on every row (this schema's own doc comment already says the two represent "the same underlying row... so the two share a rendering component" — before this fix-round that was only true for `type`/`payload`/`body`, not `actor`; task-7's report found the per-todo timeline (this endpoint, `GET /api/bff/todos/:id/events`) had no equivalent, unlike `GET /api/bff/activity`). Always present, never null — every event has a real actor by construction (DATA_MODEL.md). */
            actor: components["schemas"]["ActivityActor"];
            /** @description `created` | `commented` | `status_changed` | `assigned` | `field_changed` — the full read-side vocabulary (DATA_MODEL.md). `created` only ever appears here as a read value, never as something `POST .../events` accepted (I16). */
            type: string;
            /** @description JSON, shape depends on `type` — `{from, to}` pairs for `status_changed`, `null` for `commented`, `{field, from, to}` for `field_changed`. `assigned`'s own `{from, to}` pair is each either `null` or a `{id, handle}` snapshot resolved once, at write time, into the stored payload (milestone-4 fix-round, handle-exposure — matches my-task's own AssigneeSnapshot, `~/gits/my-task/src/server/modules/task/task.service.ts:139-142`, resolved the same way at the same moment: a later handle change never rewrites old history). */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** @description The comment text for `type: commented`, `null` otherwise. Rendered client-side through a Markdown-to-React-elements path, never raw HTML (I8's mirror, GOAL.md). */
            body?: string | null;
            clientRequestId: string;
            /** Format: date-time */
            createdAt: string;
        };
        TodoEventList: {
            events: components["schemas"]["TodoEvent"][];
        };
        /** @description Carried so the UI can mark human vs agent (I20's sibling requirement, not itself an invariant — a rendering fact, not a safety one, `_contract/API.md`). */
        ActivityActor: {
            handle: string;
            role: string;
        };
        /** @description The todo this event belongs to — enough to link/label it, not the full `Todo` shape. */
        ActivityTodoRef: {
            id: string;
            title: string;
        };
        /** @description Round-trips verbatim: the response's `nextCursor` and the request's `cursorCreatedAtMs`/`cursorId` query params name the same two values, mirrors my-task's own `{createdAtMs, id}` cursor object shape adapted to a flat query string. */
        ActivityCursor: {
            /** Format: int64 */
            createdAtMs: number;
            id: string;
        };
        /** @description One `todo_events` row, shaped for the feed — same underlying row `TodoEvent` (this file's own schema) represents on the per-todo timeline, so the two share a rendering component (`_goal/GOAL.md` Done-when 8): same `type`/`payload`/`body` meaning, plus `actor`/`todo` context a single-todo timeline doesn't need to repeat. */
        ActivityItem: {
            id: string;
            /** Format: int64 */
            seq: number;
            /** @description Full read-side vocabulary, `created` included (a read value here, never a write one — I16). */
            type: string;
            actor: components["schemas"]["ActivityActor"];
            payload?: {
                [key: string]: unknown;
            } | null;
            /** @description The comment text for `type: commented`, `null` otherwise — same Markdown-to-React-elements rendering rule as `TodoEvent. body` (never raw HTML, I8's mirror). */
            body?: string | null;
            /** Format: date-time */
            createdAt: string;
            todo: components["schemas"]["ActivityTodoRef"];
        };
        ActivityFeed: {
            items: components["schemas"]["ActivityItem"][];
            /** @description Null when exhausted. */
            nextCursor?: components["schemas"]["ActivityCursor"] | null;
        };
        ApiKey: {
            id: string;
            prefix: string;
            /** @description milestone-4 fix-round (handle-exposure): the owning agent's handle — my-task's own api-key-settings.tsx shows `{k.handle}` on every row and its revoke dialog names the agent by handle ("Revoke {handle}'s key?"); this endpoint (GET /api/bff/keys) already JOINs users for every row it returns (I21 — every key here belongs to a role='agent' user), so this is always present, never null. */
            handle: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ApiKeyList: {
            keys: components["schemas"]["ApiKey"][];
        };
        /** @description One row of GET /users' assignee-picker source. Every active user, either role — `role` rides along so a client could group/label by it, though the picker itself (`_contract/API.md`'s own reasoning for `assigneeHandle`) only ever needs `id` (to write) and `handle` (to display). */
        User: {
            /** @description The value a picker writes back — `Todo.assigneeId` / `CreateTodoEventRequest.to` for an `assigned` event both take this, never the handle. */
            id: string;
            handle: string;
            /** @enum {string} */
            role: "owner" | "agent";
            /** @description Always `true` on every row this endpoint returns (`WHERE active = true` server-side) — present on the wire anyway so this schema doesn't silently drift from `Me`'s own `{handle, role, active}` shape if that ever changes. */
            active: boolean;
        };
        UserList: {
            users: components["schemas"]["User"][];
        };
        /** @description `additionalProperties: false` so a stray `done` (milestone-1/2/3's removed field) is a `validation_error`, not silently dropped (`_contract/API.md`). No `status` field, deliberately (mirrors the public API's own `CreateTodoRequest`) — every created todo starts `open` regardless of what a caller asks for. */
        CreateTodoRequest: {
            title: string;
            assigneeId?: string | null;
            /** @enum {string|null} */
            priority?: "low" | "medium" | "high" | "urgent" | null;
            /** Format: date-time */
            dueDate?: string | null;
            /** @description I19's idempotency key, on the `created` event this endpoint's own side effect writes — required, not optional, since `todo_events.client_request_id` is `NOT NULL UNIQUE` at the schema level for every row including `created` ones. */
            clientRequestId: string;
        };
        /** @description milestone-4: `title` only — see `updateTodo`'s own description for why `status`/`assigneeId`/`priority`/`dueDate` aren't here. `additionalProperties: false` so a stray `done` is a `validation_error`, not silently dropped. */
        UpdateTodoRequest: {
            title: string;
            /** @description I19's idempotency key — this endpoint now funnels through the same single write path (I15) as every other mutation. */
            clientRequestId: string;
        };
        /** @description One shape covers all four client-postable `type` values (`_contract/API.md`) — cross-field validation (e.g. `body` required for `commented`, `to` required for `status_changed`) is the handler's job, not this schema's, mirroring the public API's own `CreateTodoEventRequest`. `type` is deliberately an open string, not an `enum`, so `"created"` and any other unrecognised value reach the handler's own dispatch and are rejected there (I16) — the same path, not a special case for one string. */
        CreateTodoEventRequest: {
            type: string;
            clientRequestId: string;
            /** @description commented — the comment text. */
            body?: string;
            /** @description status_changed — the target status (a `Todo.status` enum value; `closed` succeeds on this surface, I18). assigned — the target assignee's user id, or `null` to unassign. */
            to?: string | null;
            /** @description field_changed — which field `to` changes: `title` | `priority` | `dueDate`. */
            field?: string;
        };
        UsageTotals: {
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
            /** Format: int64 */
            turns: number;
        };
        UsageBreakdownRow: {
            /** @description The raw dimension value (an actor name, a canonicalized path, or a machine's `install_id`) — display shortening (contract's "Console display rules", `path` basename/collision handling) is the SPA's own job, not this endpoint's; this is always the ground-truth value. */
            key: string;
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
            /** Format: int64 */
            turns: number;
        };
        UsageSummary: {
            totals: components["schemas"]["UsageTotals"];
            /** @description Every distinct key for the requested group_by within the window, cost descending. */
            breakdown: components["schemas"]["UsageBreakdownRow"][];
            /**
             * Format: int64
             * @description Distinct `machine`s with at least one event inside the selected window — not lifetime.
             */
            reporting_installs: number;
        };
        UsageWindowRow: {
            /** @enum {string} */
            window: "5h" | "24h" | "today" | "week" | "month";
            /** Format: int64 */
            turns: number;
            /** Format: int64 */
            tokens: number;
            /** Format: double */
            cost: number;
        };
        UsageWindows: {
            windows: components["schemas"]["UsageWindowRow"][];
        };
        Error: {
            error: {
                code: string;
                message: string;
                hint?: string;
            };
        };
    };
    responses: {
        /** @description The request violates a request-shape or validation rule. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, expired, or wrong-role session cookie — same shape regardless of which check failed (I5). A behavior change from this package's own HTML `GET /` view: this JSON surface always answers 401, never a redirect (a `fetch` call can't follow a redirect the way a browser navigation does — the SPA's own AuthGate-equivalent hook is what turns a 401 into a redirect, client-side). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown id, or an id that exists but isn't the caller's (I3 — absence, not permission). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in owner. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every todo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoRequest"];
            };
        };
        responses: {
            /** @description The created todo. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The todo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoRequest"];
            };
        };
        responses: {
            /** @description The updated todo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTodoEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This todo's timeline, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoEventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createTodoEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoEventRequest"];
            };
        };
        responses: {
            /** @description The created event. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listActivity: {
        parameters: {
            query?: {
                limit?: number;
                cursorCreatedAtMs?: number;
                cursorId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the cross-todo feed, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityFeed"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every agent's non-revoked keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every active user, ordered by handle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUsageSummary: {
        parameters: {
            query: {
                window: "5h" | "24h" | "today" | "week" | "month" | "lifetime";
                group_by: "actor" | "path" | "machine";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Totals, a breakdown by the requested dimension, and the window-scoped reporting-install count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getUsageWindows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per fixed window, in 5h, 24h, today, week, month order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageWindows"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
