// Package bffapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bffapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for UsageWindowRowWindow.
const (
	UsageWindowRowWindowMonth UsageWindowRowWindow = "month"
	UsageWindowRowWindowN24h  UsageWindowRowWindow = "24h"
	UsageWindowRowWindowN5h   UsageWindowRowWindow = "5h"
	UsageWindowRowWindowToday UsageWindowRowWindow = "today"
	UsageWindowRowWindowWeek  UsageWindowRowWindow = "week"
)

// Valid indicates whether the value is a known member of the UsageWindowRowWindow enum.
func (e UsageWindowRowWindow) Valid() bool {
	switch e {
	case UsageWindowRowWindowMonth:
		return true
	case UsageWindowRowWindowN24h:
		return true
	case UsageWindowRowWindowN5h:
		return true
	case UsageWindowRowWindowToday:
		return true
	case UsageWindowRowWindowWeek:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Agent UserRole = "agent"
	Owner UserRole = "owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Agent:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageSummaryParamsWindow.
const (
	GetUsageSummaryParamsWindowLifetime GetUsageSummaryParamsWindow = "lifetime"
	GetUsageSummaryParamsWindowMonth    GetUsageSummaryParamsWindow = "month"
	GetUsageSummaryParamsWindowN24h     GetUsageSummaryParamsWindow = "24h"
	GetUsageSummaryParamsWindowN5h      GetUsageSummaryParamsWindow = "5h"
	GetUsageSummaryParamsWindowToday    GetUsageSummaryParamsWindow = "today"
	GetUsageSummaryParamsWindowWeek     GetUsageSummaryParamsWindow = "week"
)

// Valid indicates whether the value is a known member of the GetUsageSummaryParamsWindow enum.
func (e GetUsageSummaryParamsWindow) Valid() bool {
	switch e {
	case GetUsageSummaryParamsWindowLifetime:
		return true
	case GetUsageSummaryParamsWindowMonth:
		return true
	case GetUsageSummaryParamsWindowN24h:
		return true
	case GetUsageSummaryParamsWindowN5h:
		return true
	case GetUsageSummaryParamsWindowToday:
		return true
	case GetUsageSummaryParamsWindowWeek:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageSummaryParamsGroupBy.
const (
	Actor   GetUsageSummaryParamsGroupBy = "actor"
	Machine GetUsageSummaryParamsGroupBy = "machine"
	Path    GetUsageSummaryParamsGroupBy = "path"
)

// Valid indicates whether the value is a known member of the GetUsageSummaryParamsGroupBy enum.
func (e GetUsageSummaryParamsGroupBy) Valid() bool {
	switch e {
	case Actor:
		return true
	case Machine:
		return true
	case Path:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`

	// Handle milestone-4 fix-round (handle-exposure): the owning agent's handle — my-task's own api-key-settings.tsx shows `{k.handle}` on every row and its revoke dialog names the agent by handle ("Revoke {handle}'s key?"); this endpoint (GET /api/bff/keys) already JOINs users for every row it returns (I21 — every key here belongs to a role='agent' user), so this is always present, never null.
	Handle string `json:"handle"`
	Id     string `json:"id"`
	Prefix string `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// UsageBreakdownRow defines model for UsageBreakdownRow.
type UsageBreakdownRow struct {
	Cost float64 `json:"cost"`

	// Key The raw dimension value (an actor name, a canonicalized path, or a machine's `install_id`) — display shortening (contract's "Console display rules", `path` basename/collision handling) is the SPA's own job, not this endpoint's; this is always the ground-truth value.
	Key    string `json:"key"`
	Tokens int64  `json:"tokens"`
	Turns  int64  `json:"turns"`
}

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	// Breakdown Every distinct key for the requested group_by within the window, cost descending.
	Breakdown []UsageBreakdownRow `json:"breakdown"`

	// ReportingInstalls Distinct `machine`s with at least one event inside the selected window — not lifetime.
	ReportingInstalls int64       `json:"reporting_installs"`
	Totals            UsageTotals `json:"totals"`
}

// UsageTotals defines model for UsageTotals.
type UsageTotals struct {
	Cost   float64 `json:"cost"`
	Tokens int64   `json:"tokens"`
	Turns  int64   `json:"turns"`
}

// UsageWindowRow defines model for UsageWindowRow.
type UsageWindowRow struct {
	Cost   float64              `json:"cost"`
	Tokens int64                `json:"tokens"`
	Turns  int64                `json:"turns"`
	Window UsageWindowRowWindow `json:"window"`
}

// UsageWindowRowWindow defines model for UsageWindowRow.Window.
type UsageWindowRowWindow string

// UsageWindows defines model for UsageWindows.
type UsageWindows struct {
	Windows []UsageWindowRow `json:"windows"`
}

// User One row of GET /users. Every active user, either role — `role` rides along so a client could group/label by it.
type User struct {
	// Active Always `true` on every row this endpoint returns (`WHERE active = true` server-side) — present on the wire anyway so this schema doesn't silently drift from `Me`'s own `{handle, role, active}` shape if that ever changes.
	Active bool     `json:"active"`
	Handle string   `json:"handle"`
	Id     string   `json:"id"`
	Role   UserRole `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserList defines model for UserList.
type UserList struct {
	Users []User `json:"users"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetUsageSummaryParams defines parameters for GetUsageSummary.
type GetUsageSummaryParams struct {
	Window  GetUsageSummaryParamsWindow  `form:"window" json:"window"`
	GroupBy GetUsageSummaryParamsGroupBy `form:"group_by" json:"group_by"`
}

// GetUsageSummaryParamsWindow defines parameters for GetUsageSummary.
type GetUsageSummaryParamsWindow string

// GetUsageSummaryParamsGroupBy defines parameters for GetUsageSummary.
type GetUsageSummaryParamsGroupBy string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List every agent's non-revoked API keys (I21).
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke any agent's API key by id (I21).
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Session-check endpoint backing the SPA's AuthGate-equivalent hook.
	// (GET /me)
	GetMe(c *gin.Context)
	// GetUsageSummary Usage totals and one-dimension breakdown for a time window.
	// (GET /usage/summary)
	GetUsageSummary(c *gin.Context, params GetUsageSummaryParams)
	// GetUsageWindows Turns/tokens/cost for each of the fixed 5h/24h/today/week/month windows.
	// (GET /usage/windows)
	GetUsageWindows(c *gin.Context)
	// ListUsers List every active user, either role.
	// (GET /users)
	ListUsers(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// GetUsageSummary operation middleware
func (siw *ServerInterfaceWrapper) GetUsageSummary(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageSummaryParams

	// ------------- Required query parameter "window" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "window", c.Request.URL.Query(), &params.Window, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter window: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "group_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "group_by", c.Request.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_by: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageSummary(c, params)
}

// GetUsageWindows operation middleware
func (siw *ServerInterfaceWrapper) GetUsageWindows(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageWindows(c)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.GET(options.BaseURL+"/usage/summary", wrapper.GetUsageSummary)
	router.GET(options.BaseURL+"/usage/windows", wrapper.GetUsageWindows)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vHrtbhvHkvatFOZ9AVHZIWkp8gIr42AhJ06ixF/rDxwsosDTnClyOuzpnnT3iOY6AvYi9gr3ShZV1TMc",
	"SlRsH9jnj02RM93VVU9VPVXVH7LSNa2zaGPIzj9kHkPrbED+47GqXuEfHYZIf5XORrT8UbWt0aWK2tn5",
	"78FZ+i6UNTaKPv1/j8vsPPt/893Sc/k1zJ9473x2c3OTZxWG0uuWFsnOszc1gpfN4Fo7oyIGUP1X01Cr",
	"FsF5uFZGV7wz+M7gLLvJs+cu/uA6W319Kd/atXUbC7rKSRhFnyDWKgK+1yEGWHQRdLBHEWKNUCpj0B8F",
	"mFx+C//73/8DahHQlpiDdRFa9I0OQTt7PLuydJC3VnWxdl7/F/4TDvOMNrerHPB9qz3KkTbe2dXUO4MQ",
	"kIWD0rm1RpY/qAZBbOFxpXxlMARwS9jUuqyhrLFcw1JpgxVMLh8ez+ACFlira+08lLWyK4Sldw3EWgdo",
	"VblWKzwKQDr96c2zp1D8+OQNzAu41rg5l6d+fv3iOYTOL1WJoMxGbQMoGzboA5w9OMnB4jV6xkqlPZYR",
	"JgqKJcayLtgCUCoyyNIZ4zbj58hEG7UFBQvvNgE9WHWtV4KuymHgM9NTr19eJCkvulj/qCJO8Y9OXyuD",
	"NkLt3Bp0gA0BIXbeEnLPHpyAttGNNsyhNBptnAZdodj8Jk9WZIe7aPUvuKVPrXct+qjFEUuPKmJ1wUhY",
	"Ot+omJ1nFYkRdYNZnsVti9l5FqLXdkVQEpuGz3mlVrYySM/v46TRBkN0FqdnsNTvp558DSby+BTfty50",
	"Ho/PWVNuY7VdgVqhjUcB5CHWY7OdRhXWSY+q1dM1bqcBY9R2FWYxvIdQu02A4sN6Ju/dFOAskHm34Ml2",
	"tgIdA3i8dmuESivjVmBVg4E3511hse23nVxlr+TRD2nBowBr3P77VXb8SNCFtmqdthEmjDzV6vliuZyv",
	"cRuOQRmPqtrCzy8unwfoAkFu6fxIIh3Bo5h8cnl6wgeVX9e4hRo9wgKNs6sAAgVn8G9Hoh1e8DiH4EQU",
	"HXp4tx4D2thD23bGEFoO2ExznLjzdetxqd8f+Okmzyikkrtn57/S68PDAwDyEd7GQPpt2N8tfscy0kaC",
	"2KdaUsQ+akmH9L+O2ISPRakE/ZthD+W92t4RmNc8JIhEuTsy4OGvS1fhQcXVWsLtnR8aDEGt8OMq5aV3",
	"z9+V9dbzIuGhIz3Du4KrMurrsRQL5wwqu++/d6Qn2H1c9MH+/Hjeb3ZItrd0uMce1bpyG/vKbVi4qtIU",
	"M5R5ORJ6qUzA/I4Bwq3I5LqFGYUl2zUL9LTVWiLiAbqgNlDpBi1nqWtlOoSJsqDK6DxHhRwUBX9ndakM",
	"JVVoVawldUOjylpbyj6FtiEqY97pqjhmF650aI3aUkDyETmiTSgZe1VSVLvKvnM2UI7sHyQuEq6yHAra",
	"oYCFCkgSzEtnjGYBWbvaro7J0feTyu9uIZRgLyQdhUe3AwO9tuL4O42+i7Wc+p7YEN0abdjTsrbxX892",
	"z2obcSVa5hj2Sc/e9chs2CsXw/bL3Yuc113TKL/9TNAserzdxcMTjrmVDlHbMnLwpUAdd6wSK9Zc+26x",
	"hY2OtbaS/7Wt3CYHkhtoTbSVtqtZln9a3LrrCHdCGOmrdZ7S3LuEtHD3BN/3shcJmEVgOUFFMKhCBGeR",
	"couNoC0xCJY/oMGSDicHYfQSkoxeIiV6OsinmN9FZT7tsG/k0ds4SCvkIysdPPi9mHgziPB14sg/xx0+",
	"0xH+zlb7qvHzK507zwRxnGVt19DhH9ZZnp2e1RwQKkWBYYO4pnTobKxHargnA6Ulezlux5WPqPFzwbPZ",
	"vfXpvr6z2Me4Sr/8YanR340BLywyq3RLYDbKjHMGEtwkGzNpzAF1rNEznWSXL+hTAV5XVDYT4SRaqVLB",
	"AaXrTIp/c6MWaIgk6yiJ4z6GsS/bhWSgIvoOb9HyfSI98OHi7z89efWkl/tvIG8G9NfopQRi0RPZpSUl",
	"IHsEZbdUmPXMWAzAJRlVckFT2WW2UHm9jFJQFs+wSNm0SGQ/Z/XkSYCbIhWuepkqdqLWUpOGvQz6aZTq",
	"HubdM63eJdzGoicuRZT/4w7AhPyzeBj6w+ybsfMZ0E7+/1eAliUPMFpSh126wzTt8Q8/HIW+mTBVXazR",
	"Rl1SgbFf2092hea3UMzKWuNyPvpu/q6nYPOLl5ezpiqOKW/b0DVYgbNmS6hOzAp8Z5m3pTzPdkgASdV+",
	"71h922ksWgAnTYWgVxarHH6KsX1BW+x3RXLwGJy5xor2Lig6eqvMPHplA+U+qiZ7YPavNrqqDG6UR5gU",
	"i+Vy9kqUTNp4Lc8kHkqZfLEldyDCkg5DDtFieQ7WQRGw7LyO20KcBIksVlga5bGS+tNZaDvfuoD5wInw",
	"vSqjdHM8quAsFK5Fq1o926rG9ALXqCpyEtc05KErfY0hraEiLLXB8508R4F4LO2fFDrvm4nwDXveN+Pm",
	"3aRYaTvdaYJsSaclI8zgAgKWzlY5aFthi7ai/WnD5O170o6OCJPiDkrgKnuzcSxjkE2cxavseOjutN3C",
	"6BIuXl7C5DEqj34fprk0FqZLVTJ/V7aSYz/+4Ycdeg8iPBfgpVeHPhOB9RgIAHHjiLb+zqGz9c4tp245",
	"1XReHbfQIEUoHZpAOCCwR9+VosHL0/nlyelxzvIQUu3KcHeOTE+nFYVtOPYvTJfMtqDyQfktc0mItetW",
	"tXQrXYWAdul8iUGyw/do9AK9imi20ryMo/5dOjo3fjwjzzqm3jqETtmSG7beRbH4kCD44QmB9+WL12+A",
	"ey0FGUaeTWlhBE7S3EF8Fvzu/IOubop9lJ6D4vqQpJH23wJTZiLlqCUdSFzcwk9v3ryEHqzcjxkOQKod",
	"ThCi2sJ3Ty+nHGsONUB7MFDFFtZcNt7FYw7FXlRbOWXmP764eMpg/Z6+3dRo4eHx7MrKEQvuIm0gtMqG",
	"lHmLcS+pYF6Q1EJv9PXkro3bR8DJ5emJqHgnxen821GMFsiG0rWkK2wUoTnARLDXeWUIDcIHsGnjNifw",
	"lbgzvyRX0iJWEF0vq4hQ5HB5Kuh/9eTl04vvnnzPmBCR19hGYTBc4yiwuBmwM4NCSFHBx0jnlc7utGuP",
	"wXAXHj9OmNIZe91Ys8355al8bLT3jjL0rbZlQavNYijAuy6il0hqtolA6EjZP6N3iLhygLh4eZnl2TX6",
	"IDnxZPZg9oBybUJ0dp59O3sw+5aYmIo1p+p53ztbYbyv2D1sf+vsVNqjFeMAJkX6852KcPkanr99+rQP",
	"tr934TBG6Kh9dNz7LXUka2eqAIqtrchchvYZ23jndQkFziLbnf2LsEXK5TAS3WhYksJVQpd4bA8y8bGN",
	"CneQq8rYKQOLbjWDV3t+ye3L7Tm5eRpzTBddnHZ2pCQIURuTus9dK7QzUQY6BwRE0BEsYhVSOLCrGTxR",
	"Zc0EuFTe69SDvtUAL4TMFTDZ9XIFgBxDaEdFYc6k9vLPLy6fUx6ouhIrcSOPtA+rqg9Sfdd4LGREY2BT",
	"UxJMTih/LHDpPErPnCRzNjWMiC1yYLussvOMWOQvhLp8fwh4+uDBFxtFjbrFB+ZRqcxJirsNZJ70nT04",
	"uW+PQej53hSNJyx9t4kP2UeHA/sQAxCnoRg545d3KUYc0WA8UB29xhhg5GnFDJ67CCmGcuv/KhvGgW5j",
	"rzK2UnKyIXuGTkzNdhKbS6RiuAxcg+InzxPt7iBs9AoatZVcx6LkQ1BfMeGmZWZwYaEbJpm0c3H24Iwi",
	"wrslkYMiF8enDHyV3TOzvMpSPSXqdBxex5ljuthOreOzTA0u4zQ6+QWMc+uuHQ7Yn6oLGEhte7yAM/BA",
	"DXYkgirEnt6OV8mhGnMWVtKXYALze1jApCibas4xbrrGbXH8abzgkAfKqOoX7qfecsGzu4iTp6t/1C3o",
	"pbOPvzSM1vf9KE3VxvBLvsONhWpwIMppXjUYuRj99UOmSXbKc1meWdVwS6nKxnVm9B3mo4Byu2D+jZyy",
	"wXuz42shjqn0EIyqcIvoU2QeBn7XJ/MGiwPIcfbOSlT9XGWb2oFq4DK/yv7S3iqQiQ7Y+keMz/Brhtpn",
	"eN8tC6lopzpl9C8SV1PVOpULAIOTLlS5ljTfTzvuG5+nWNsFtcJ52E0HDlo4ROe305N51OUa4/Tk7DzV",
	"LzyTSfTFo6oGO7B/F7z6O26hE4Es3vHUZj6bzfsVd1y9/0CcnCc+hO+0HIU+lCKMUMIdq6VGU6VRtHB1",
	"4rdEc7CCa/QLFXXT104qQr8+Vbil6Squ7imHBKvW+K5UAQso+olFMS/uttKLnhHt4Zbb7+FulZbUUqoG",
	"zXcqsLpIE1yamYAcTR9xkL/KSuc9jxWuMinXhN8nLbPgMsWif9gKRwGMjuiVAW3bLkq6CK5ByWbRgUdi",
	"vMczKKQzWqThhfjmryEqz69tjsHzTZFJwV3kYl5sENfFvOAuciGaJexUyk+VLWtHFa+K8PbNd9DoyupV",
	"HefPnK3Udn4S4iMoHtbFvDg9Sy97Z3gS92ikYWh1uQ69RoexIolWDCMNet0rJldr3HLTZwaFjD5m0qsu",
	"IHRNYEq8dJ3n3CPFQOk6S3GQkmga5ExYV/Av4LooH0pV1viOwdv/wdN47WxK+X2h348epdOf74ZfYnq2",
	"CvwbY1eoJ7kVVnIphSkl52yKYJ1BUAvXSTHwDXkDVt+QnFPBdelM19jQA26/4ct5sGeqVehvLXjceB0p",
	"pR/Cbj8EZaVQ4KzuzL9kuPkPTcEm4xHYrtFDlfZRgFb5qJWZXmsk7n6NKuYjqibXeHhyGFi0Peqdag2z",
	"hZKiSphd2Stb9HvxuchE7/vhbA4ykbjGodDZDZK5etXvsYIlPTBuFtwKQKPwMwQfiTapAiWM/3l6Vv/J",
	"PvMnecyf4i9y/qVRqxW5Ccm36LSp+CIQVFjKfFrbHjQnZ0MMJbslV+6b7qqqsJKIO7g+Pdy4klgdN55E",
	"MuK8vWJ4wEqBU2I7RG2wh5Mlm7KeUfQwxJg0QuH6Ru58wYShW8sxiJoQi6PQcTyD/+jQb6fCFKaD2hmf",
	"PCRJQxXKMWnl4mhkg6gWhjlaZ6PryprpM5eGvY4jV1QkYy69WBXB+Qr9DEYQEGAkYixYlX6IXckgumsJ",
	"C9ZtcgG3dUAMWc5zD13Ym5sfplV/0PF3vGoYpt3PrT51cJcPdjw4wji8fx9aP0kCvrSRWiC0rcSAQ7v9",
	"9hVZ056SD/EnjvQ53xhMKaGfOeyuGQzJI0+d4v6WQd9SG8LhNIVDiYKJiT34OBMbXcz9AuSNDw2SxFhi",
	"Z3G6y4C7ky753gx7sxxoj7WNpqmfytqIH4Zb3I2Wn6YwLg45MHG34dQpztpf3OBwQEfuSPdD3bpRWyhW",
	"+24ztI17/jE4Ub9AkOuFxD52rjniCBJ8+OJfYj8B/bVmdrWpncGdbUe8K6l2GJz0onNYbY3mGc+g8OO/",
	"CgD9oPtr+0C/zwEfeHGvKbSFh3UOp2d1DhxGcqAokgMHkRQovwRi33TehrnwrTnf3OFbmcxp+jRCgj2s",
	"56dn9ZxlmZMoc5EkQXWAb5qUHoTtM+4Eh4/1gSeF0SEWqZN8aPQNL159/+QVPP7PdDu1yOEqq7tGWfE6",
	"LqQDKZHATqtdZccz4JYVrcrzPrmZycOSrq36j9KVunXLNglGmXKXYCl9SSt8CE5D7ylNAokdvi+RmGKc",
	"wYsDfXJ2sKjRE5kYt39GlHCv9ngElL/5cq6IA4suaEslM8V/BrpdpQ7oZCzTqEw8NKQcTe6kDX18X2vz",
	"LRv5q7pNmsTf39kczyPYGWRqLHD44v3Ne6YfMxFQrmEIeei8yc6z/u5zdvPbzf8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
