// Package bffapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bffapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for UsageWindowRowWindow.
const (
	UsageWindowRowWindowMonth UsageWindowRowWindow = "month"
	UsageWindowRowWindowN24h  UsageWindowRowWindow = "24h"
	UsageWindowRowWindowN5h   UsageWindowRowWindow = "5h"
	UsageWindowRowWindowToday UsageWindowRowWindow = "today"
	UsageWindowRowWindowWeek  UsageWindowRowWindow = "week"
)

// Valid indicates whether the value is a known member of the UsageWindowRowWindow enum.
func (e UsageWindowRowWindow) Valid() bool {
	switch e {
	case UsageWindowRowWindowMonth:
		return true
	case UsageWindowRowWindowN24h:
		return true
	case UsageWindowRowWindowN5h:
		return true
	case UsageWindowRowWindowToday:
		return true
	case UsageWindowRowWindowWeek:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Agent UserRole = "agent"
	Owner UserRole = "owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Agent:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageSummaryParamsWindow.
const (
	GetUsageSummaryParamsWindowLifetime GetUsageSummaryParamsWindow = "lifetime"
	GetUsageSummaryParamsWindowMonth    GetUsageSummaryParamsWindow = "month"
	GetUsageSummaryParamsWindowN24h     GetUsageSummaryParamsWindow = "24h"
	GetUsageSummaryParamsWindowN5h      GetUsageSummaryParamsWindow = "5h"
	GetUsageSummaryParamsWindowToday    GetUsageSummaryParamsWindow = "today"
	GetUsageSummaryParamsWindowWeek     GetUsageSummaryParamsWindow = "week"
)

// Valid indicates whether the value is a known member of the GetUsageSummaryParamsWindow enum.
func (e GetUsageSummaryParamsWindow) Valid() bool {
	switch e {
	case GetUsageSummaryParamsWindowLifetime:
		return true
	case GetUsageSummaryParamsWindowMonth:
		return true
	case GetUsageSummaryParamsWindowN24h:
		return true
	case GetUsageSummaryParamsWindowN5h:
		return true
	case GetUsageSummaryParamsWindowToday:
		return true
	case GetUsageSummaryParamsWindowWeek:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageSummaryParamsGroupBy.
const (
	Actor   GetUsageSummaryParamsGroupBy = "actor"
	Machine GetUsageSummaryParamsGroupBy = "machine"
	Path    GetUsageSummaryParamsGroupBy = "path"
)

// Valid indicates whether the value is a known member of the GetUsageSummaryParamsGroupBy enum.
func (e GetUsageSummaryParamsGroupBy) Valid() bool {
	switch e {
	case Actor:
		return true
	case Machine:
		return true
	case Path:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`

	// Handle milestone-4 fix-round (handle-exposure): the owning agent's handle — my-task's own api-key-settings.tsx shows `{k.handle}` on every row and its revoke dialog names the agent by handle ("Revoke {handle}'s key?"); this endpoint (GET /api/bff/keys) already JOINs users for every row it returns (I21 — every key here belongs to a role='agent' user), so this is always present, never null.
	Handle string `json:"handle"`
	Id     string `json:"id"`
	Prefix string `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// UsageBreakdownRow defines model for UsageBreakdownRow.
type UsageBreakdownRow struct {
	Cost float64 `json:"cost"`

	// Key The dimension value to display: an actor name, a canonicalized path, or — group_by=machine, story-1/ticket-18 — the reporting machine's `hostname` (joined from `machines` on `usage_events.machine` = `machines.install_id`), not the raw `install_id`, falling back to the raw `install_id` itself if a machine has events but no corresponding `machines` row. Display shortening beyond this substitution (contract's "Console display rules", `path` basename/collision handling) is still the SPA's own job, not this endpoint's.
	Key string `json:"key"`

	// RawKey Present only when `key` has been substituted for a friendlier display value (currently: group_by=machine, where `key` is the hostname) — carries the ground-truth raw value (`key`'s own former meaning: the machine's `install_id`) so the console can still surface it, e.g. via a tooltip (contract's "machine label" rule — same "shortened label, full value still reachable" pattern as `path`). Absent for every other group_by, since `key` is already the raw value there.
	RawKey *string `json:"raw_key,omitempty"`
	Tokens int64   `json:"tokens"`
	Turns  int64   `json:"turns"`
}

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	// Breakdown Every distinct key for the requested group_by within the window, cost descending.
	Breakdown []UsageBreakdownRow `json:"breakdown"`

	// ReportingInstalls Distinct `machine`s with at least one event inside the selected window — not lifetime.
	ReportingInstalls int64       `json:"reporting_installs"`
	Totals            UsageTotals `json:"totals"`
}

// UsageTotals defines model for UsageTotals.
type UsageTotals struct {
	Cost   float64 `json:"cost"`
	Tokens int64   `json:"tokens"`
	Turns  int64   `json:"turns"`
}

// UsageWindowRow defines model for UsageWindowRow.
type UsageWindowRow struct {
	Cost   float64              `json:"cost"`
	Tokens int64                `json:"tokens"`
	Turns  int64                `json:"turns"`
	Window UsageWindowRowWindow `json:"window"`
}

// UsageWindowRowWindow defines model for UsageWindowRow.Window.
type UsageWindowRowWindow string

// UsageWindows defines model for UsageWindows.
type UsageWindows struct {
	Windows []UsageWindowRow `json:"windows"`
}

// User One row of GET /users. Every active user, either role — `role` rides along so a client could group/label by it.
type User struct {
	// Active Always `true` on every row this endpoint returns (`WHERE active = true` server-side) — present on the wire anyway so this schema doesn't silently drift from `Me`'s own `{handle, role, active}` shape if that ever changes.
	Active bool     `json:"active"`
	Handle string   `json:"handle"`
	Id     string   `json:"id"`
	Role   UserRole `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserList defines model for UserList.
type UserList struct {
	Users []User `json:"users"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetUsageSummaryParams defines parameters for GetUsageSummary.
type GetUsageSummaryParams struct {
	Window  GetUsageSummaryParamsWindow  `form:"window" json:"window"`
	GroupBy GetUsageSummaryParamsGroupBy `form:"group_by" json:"group_by"`
}

// GetUsageSummaryParamsWindow defines parameters for GetUsageSummary.
type GetUsageSummaryParamsWindow string

// GetUsageSummaryParamsGroupBy defines parameters for GetUsageSummary.
type GetUsageSummaryParamsGroupBy string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List every agent's non-revoked API keys (I21).
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke any agent's API key by id (I21).
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Session-check endpoint backing the SPA's AuthGate-equivalent hook.
	// (GET /me)
	GetMe(c *gin.Context)
	// GetUsageSummary Usage totals and one-dimension breakdown for a time window.
	// (GET /usage/summary)
	GetUsageSummary(c *gin.Context, params GetUsageSummaryParams)
	// GetUsageWindows Turns/tokens/cost for each of the fixed 5h/24h/today/week/month windows.
	// (GET /usage/windows)
	GetUsageWindows(c *gin.Context)
	// ListUsers List every active user, either role.
	// (GET /users)
	ListUsers(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// GetUsageSummary operation middleware
func (siw *ServerInterfaceWrapper) GetUsageSummary(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageSummaryParams

	// ------------- Required query parameter "window" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "window", c.Request.URL.Query(), &params.Window, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter window: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "group_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "group_by", c.Request.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_by: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageSummary(c, params)
}

// GetUsageWindows operation middleware
func (siw *ServerInterfaceWrapper) GetUsageWindows(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageWindows(c)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.GET(options.BaseURL+"/usage/summary", wrapper.GetUsageSummary)
	router.GET(options.BaseURL+"/usage/windows", wrapper.GetUsageWindows)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFt/bxtHc/4qg2sBkemRtBS5aBUEhRw7iRL/qi3jRREFvuXdkLfmcveyuyeadQT0Q/QT9pMUM7N3PEpU",
	"bL+w338SirzbnZ15ZuaZmfWHrHTrxlm0MWRnHzKPoXE2IP/xSFWv8I8WQ6S/SmcjWv6omsboUkXt7Oxd",
	"cJa+C2WNa0Wf/tnjIjvL/mm2W3omv4bZE++dz25ubvKswlB63dAi2Vl2WSN42QyutTMqYgDVfTUJtWoQ",
	"nIdrZXTFO4NvDU6zmzx77uKPrrXV15fyjV1Zt7Ggq5yEUfQJYq0i4HsdYoB5G0EHexQh1gilMgb9UYDR",
	"xbfwf//zv6DmAW2JOVgXoUG/1iFoZ8fTK0sHeWNVG2vn9X/jP+Awz2hzu8wB3zfaoxxp451dTrwzCAFZ",
	"OCidW2lk+YNaI4gtPC6VrwyGAG4Bm1qXNZQ1litYKG2wgtHFw/EUzmGOtbrWzkNZK7tEWHi3hljrAI0q",
	"V2qJRwFIpz9fPnsKxU9PLmFWwLXGzZk89cvrF88htH6hSgRlNmobQNmwQR/g9MFxDhav0TNWKu2xjDBS",
	"UCwwlnXBFoBSkUEWzhi3GT5HJtqoLSiYe7cJ6MGqa70UdFUOA5+Znnr98jxJed7G+icVcYJ/tPpaGbQR",
	"audWoANsCAix9ZaQe/rgGLSNbrBhDqXRaOMk6ArF5jd5siI73Hmjf8UtfWq8a9BHLY5YelQRq3NGwsL5",
	"tYrZWVaRGFGvMcuzuG0wO8tC9NouCUpi0/A5r9TKVgbp+X2crLXBEJ3FySks9PuJJ1+DkTw+wfeNC63H",
	"8Rlrym2stktQS7TxKIA8xHpcbydRhVXSo2r0ZIXbScAYtV2GaQzvIdRuE6D4sJrKezcFOAtk3i14sp2t",
	"QMcAHq/dCqHSyrglWLXGwJvzrjDfdtuOrrJX8uiHtOBRgBVu/+MqG38n6EJbNU7bCCNGnmr0bL5YzFa4",
	"DWNQxqOqtvDLi4vnAdpAkFs4P5BIR/AoJh9dnBzzQeXXFW6hRo8wR+PsMoBAwRn8/ki0wwuOcwhORNGh",
	"g3fjMaCNHbRtawyh5YDNNMeJO183Hhf6/YGfbvKMQiq5e3b2G73eP9wDIB/gbQik3/v93fwdlpE2EsQ+",
	"1ZIi9lFLOqT/64jr8LEolaB/0++hvFfbOwLzmocEkSh3RwY8/HXpKjyouFpLuL3zwxpDUEv8uEp56d3z",
	"d2W99bxIeOhIz/Cu4KqM+nooxdw5g8ru++8d6Ql2Hxe9tz8/nnebHZLtDR3ukUe1qtzGvnIbFq6qNMUM",
	"ZV4OhF4oEzC/Y4BwKzK5dm4GYcm26zl62molEfEuXaj0Gi1nqGtlWiQHq3RojNqeUWZWZXSeg0MOinKA",
	"s7pUhnIrNCrWnO7IX5fetc3b+fb7tSprbTGHEJ3fTo5nUZcrjJPjf+sTgcfGeQpYkB4+ClDULkTap4DR",
	"O6ctVpLjivRI4ChWtKSyt3hNsJ+mnwr4fvfYVNsQlTFvdVWMhSLwlmoDxeCnHBbKGBJhrsoVnfrQUxQn",
	"0SxAL0B1skKtAogATFSsg9J5oXwVLTiQ2LvNFB6LOiku+4gc2Oe4dbaSgBXaeYg6tpwvR0RWvCop6l9l",
	"PzgbiEMkgzBXC1dZDgWpvoC5Ckgqm5XOGM1GZPRpuxxTIAxRG3Mr9b5z804rg8B9FO4JjV5t3h7EzkuJ",
	"ruCs2cKmRgvFCrcFa2eOaHfnIksSzYOF10jSoe9PJJgbla33aKPZnh3A0YYTgKyuJUV1WBkzpErlvU7J",
	"a8l5dRJ9G2s2Z9qBX08qIHdBD2tUZAzJuAMgDgEkaQWhTJYolU1a7biUjjngdDmFa61AQXTORN3cMmQH",
	"HaPmaK4yNuSOCl5lCRpYyRM5LFpjkuiynUdV1mpu8Cojv4voLaiQgEAMcc7W2OVVF2v0vTZzCNqWAy12",
	"SblDfXJ+UvU9SIhuhTbshRtt47+e7p7VNuJSwg0n80969m5qyvq9colw3XL3htDX7Xqt/PYzo+e8C7x3",
	"wf2EVVjpELUtI7MQ0mzclVdY9bqFjY61tkKEta3cJgeSG2hN5JgwzfJPS+B3M8KdXE76SuHzbYJquHuC",
	"x53sXTQqAssJKoJBFchxUcIYaEtUmuUPaLCkw8lBGKMULIxeIDFeOsinmN9FZT7tsJfy6G0cpBXygZUO",
	"HvxeTFz2InydhPqPcYfPdIS/sdW+KpH4SufOM0Ec003brunwD+ssz05Oaw4IlaLAsEFcES90NtYDNdxD",
	"xdKSnRy348pH1Pi54Nns3vp0X99Z7GOkvVv+sNTo78aAFxa5vHIL4LKMS68pSHATWsrVUw6oOVtww4Jc",
	"vqBPBXhdIaUKZ5eUCFWqvKF0rUnxb8YJi6pFHSVx3Ee192U7lxqtiL7FW/XpfkXZF4bF335+8upJJ/f3",
	"IG8G9NfopRfAojc9L0kB2SMou90QAUslohiAexP2KELQhrkHVF4vYmKdz7BjC0WqenNWT54EuClSB0cv",
	"UuuKakxpzuxzqU+rLe4pQbuSo3MJt7Hoqaig2vfjDsCV6WcVJOgPl6GMnc+AdvL/vwK0LHmgtCN12IU7",
	"XK88+vHHo9B11SaqjTXaqEuqtPebXKNdx+VbKKZlrXExG3w3e9tRtNn5y4vpmssF4nntGiuhtfNtR57B",
	"t5aZe8rzbIcEkNT26hyr678ORQvgpLsW9NJilcPPMTYvaIv99mAOHoMz11jR3gVFR2+VmUWvbKDcN5sv",
	"Fh0wu1fXuqoMbpQnmjtfLKavRMmkjdfyTDHuM/l8S+5AhCUdhhyiwfKMCpkiYNl6HbeFOAkSVaywNMpj",
	"JY0YZ6FpfeMC5j0nwveqjMJlPapAdZpr0KpGT7dqbTqBa1QVOYlbr8lDl/oaQ1pDRVhog2c7eY4ClSq0",
	"f1LorOuqwzfsed8Mu9ijYqntZKeJrvQjI0zhHAKWzlY5aFthg7ZirqxN6qPuSzs4IoyKOyiBq+xy41jG",
	"IJs4i1fZuK9um3ZudAnnLy9g9AiVR78P01w6bJOFKrlQU10l+OjHH3foPYjwXICXXu0brgTWMRAA4obL",
	"93ccOhvv3GLiFhNN59VxC2ukCKXDOhAOCOzRt6Vo8OJkdnF8Ms5ZHkKqXRpuU5Pp6bSisA3H/rlpk9nm",
	"VG8pv2UuCbF27bJOJVOFgHbhfIlBssNjNHqOXkU0W+nix0EjOx39TKoQsrx1TL11CK2i6sVRiopi8T5B",
	"8MMjAu/LF68vgZuOBRlGnk1pYQBOrtEP4bPgd2cfdHVT7KP0DBRXSSSN9MHnmDITKUct6EDi4hZ+vrx8",
	"CR1YuTHZH4BU258gRLWFH55eTDjWHJoE9DVmABVWJPcBPOZQ7EW1pVNm9tOL86cM1sf0LZfnD8fTKytH",
	"LLiduoHQKBtS5i2GTdWCeUFSC72xa6R0UaeLgKOLk2NR8U6Kk9m3gxgtkA2la0hXuFaE5gAjwV7rlSE0",
	"CB/AdRP7YrU3vyRX0iJWEF0nq4hQ5HBxIuh/9eTl0/MfnjxmTIjIK2yiMBiucRRY3PTYmUIhpKjgY/Tt",
	"AWPcZtI2YzA8jsKPE6Z0xk431mxzfnkiH9fae+e54bXXvy9otWnkTlEb0UskNdtEIHSk7J/RO0RcOUCc",
	"v7zI8uwafZCceDx9MH1AuTYhOjvLvp0+mH5LTEzFmlP1rGsiLzHeV+wetr91diJzgopxAKMi/flWRbh4",
	"Dc/fPH3aBdt3bTiMETpqFx33fkut+dqZKoBiaysyl6F9hjbeeV1CgbPIdmf/ImyRcjmMpFaeTA1TuEro",
	"Eo/tQCY+tlHhDnJVGVtlYN4up/Bqzy+5jy+d0TTvm8zbOGntQEldg4jHMG3TtZDkwNxAQgQdwSJWIYUD",
	"u5zCE1XWTICH/axbk6BCyFwBo91QQwDIMYR2VBTmTJqz/PLi4jnlgaotsRI34k6SqKoLUt34ZChkRGNg",
	"U1MSTE4of8xx4TzK8IgkczY1jIgtcmC7qLKzjFjkr4S6fH8afvLgwRebyQ7GJgcGs6nMSYq7DWQeeZ8+",
	"OL5vj17o2d44mUeNXbeJD9lFhwP7EAMQp6EYOeWXdylGHNFgPFAdvcYYYOBpxRSeuwgphvIM7Crr5+Ju",
	"Y68ytlJysj57hlZMzXYSm0ukYrj0XIPiJw/W7e4gbPQK1moruY5FyfugvmTCTctM4dxC24/0aefi9MEp",
	"RYS3CyIHRS6OL63Oe4b3V1mqp4bdy2HmmMy3E+v4LBODiziJTn4B49yqbfoDdqdqAwZS2x4v4AzcU4Md",
	"iaAKsaO3w1VyqIachZX0JZjA7B4WMCrKdTXjGDdZ4bYYfxovOOSBMrP9lfupt1zw9C7i5Onq73ULeun0",
	"4y/1d0z2/SiNl4fwS77DjYWqdyDKaV6tMXIx+tuHTJPslOeyPLNqzS2lKhvWmdG3mA8Cyu2C+XdyyjXe",
	"mx1fC3FMpYdgVIVbRJ8icz/5vj6erbE4gBxn76xE1c9VtqkdqDVc5FfZX9pbBTLRAVv/hPEZfs1Q+wzv",
	"u24kFe1Ep4z+ReJqqlonchOmd9K5KleS5ruB1n33SFKs5WHhLOymAwctfHtOeXo2HPkk+uJRVb0d2L/3",
	"RpEFMXMez82m01m34o6rdx+Ik/NEiPCdlqPQh1KEEUq4Y7XQaKp0J0O4OvFbojlYwTX6uYp63dVOKkK3",
	"PlW4pWl5DqkphwSrVvi2VAELKLqJRTEr7rbSi44R7eGW2+/hbpWW1FKqNZofVGB1kSa4NDMBOZp+x0H+",
	"KuP5aBmxusqkXBN+n7TMgstkj/7DVjgKYHRErwxo27RR0kVwa5RsFh14JMY7nkIhndEiDS/EN38LUXl+",
	"bTMGz1emRgV3kYtZsUFcFbOCu8iFaJawUyk/UbasHVW8KsKbyx9grSurl3WcPXO2UtvZcYjfQfGwLmbF",
	"yWl62TueJI+/G2gYGl2uQqfRfsZOohX9SINe94rJ1Qq33PSZQiGjj6n0qgsI7TowJV641nPukWKgdK2l",
	"OEhJNA1yRqwr+BdwbZQPpSprfMvg7f7gayna2ZTyu0K/m8hKpz/fDb/E9GwV+HfGrlBPcius5HYWU0rO",
	"2d1wU81dK8XAN+QNWH1Dck4E16Uz7dqGDnD7DV/Ogx1TrUJ3fcfjxutIKf0QdrvBMCuFAmd1Z/4lI86/",
	"awo2Go7Ado0eqrSPAjTKR63M5FojcfdrVDEfUDW5z8aTw8Ci7VHvVGuYLZQUVcL0yl7ZottLRrUQ9PtY",
	"i/w5yETiGvtCZzdo5upVv8cKFvTAsFlwKwANwk8ffCTapAqUMP7nyWn9J/vMn+Qxf4q/yPkXRi2X5CYk",
	"37zVpuIbcVBhKRcRtO1Ac3zax1CyW3Llrumuqgoribi969PDa1cSq+PGk0hGnLdTDA9YKXBKbIeoDXZw",
	"smRT1jOKHvoYk0YoXN/I5UcYMXRrOQZRE2JxFDrGU/jPFv12Ikxh0qud8clDkjRUoRyTVi6OBjaIam6Y",
	"o7U2urasmT5zadjpOHJFRTLm0otVEZyv0E9hAAEBRiLGglXph9ilDKLbhrBg3SYXcFsHxJDlPPfQhb25",
	"+WFa9Qcdf8er+mHa/dzqUwd3eW/HgyOMw/t3ofWTJOBrS6kFQttKDDi02+9fkTXtKfkQf+JIn/PV2ZQS",
	"upnD7ppBnzzy1Cnubhl0LbU+HE5SOJQomJjYg48zscEN9S9A3vjQIEmMJXYWJ7sMuDupXApib5YD7bG2",
	"wTT1U1kb8cNwi7vR8pMUxsUheybuNpw6xVm7ixscDujIfG+pr1s3agvFct9t+rZxxz96J+oWCHLPltjH",
	"zjUHHEGCD9+ATewnoL/WzK42tTPDm3I73pVU2w9OOtE5rDZG84ynV/j4rwJAN+j+2j7Q7XPAB17cawpt",
	"4WGdw8lpnQOHkRwoiuTAQSQFyi+B2MvW2zATvjXjmzt8jYo5TZdGSLCH9ezktJ6xLDMSZSaSJKj28E2T",
	"0oOwfcad4PCxPvCoMDrEInWSD42+4cWrx09ewaP/Ste0ixyusrpdKytex4V0ICUS2Gm1q2w8BW5Z0ao8",
	"75MryjwsaZuq+yhdqVvXzZNglCl3CZbSl7TC++DU957SJJDY4fsSiSnGKbw40CdnB4saPaiw1/4ZUMK9",
	"2uM7vpjKt9RFHJi3QVsqmSn+M9DtMnVAR0OZBmXioSHlYHInbejxfa3NN2zkr+o2aRJ/f2dzOI9gZ5Cp",
	"scDhi/c375l+TEVAuYYh5KH1JjvLun8EkN38fvP/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
