// Package bffapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bffapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for UsageWindowRowWindow.
const (
	UsageWindowRowWindowLifetime UsageWindowRowWindow = "lifetime"
	UsageWindowRowWindowMonth    UsageWindowRowWindow = "month"
	UsageWindowRowWindowN24h     UsageWindowRowWindow = "24h"
	UsageWindowRowWindowN5h      UsageWindowRowWindow = "5h"
	UsageWindowRowWindowToday    UsageWindowRowWindow = "today"
	UsageWindowRowWindowWeek     UsageWindowRowWindow = "week"
	UsageWindowRowWindowYear     UsageWindowRowWindow = "year"
)

// Valid indicates whether the value is a known member of the UsageWindowRowWindow enum.
func (e UsageWindowRowWindow) Valid() bool {
	switch e {
	case UsageWindowRowWindowLifetime:
		return true
	case UsageWindowRowWindowMonth:
		return true
	case UsageWindowRowWindowN24h:
		return true
	case UsageWindowRowWindowN5h:
		return true
	case UsageWindowRowWindowToday:
		return true
	case UsageWindowRowWindowWeek:
		return true
	case UsageWindowRowWindowYear:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Agent UserRole = "agent"
	Owner UserRole = "owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Agent:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageSummaryParamsWindow.
const (
	GetUsageSummaryParamsWindowLifetime GetUsageSummaryParamsWindow = "lifetime"
	GetUsageSummaryParamsWindowMonth    GetUsageSummaryParamsWindow = "month"
	GetUsageSummaryParamsWindowN24h     GetUsageSummaryParamsWindow = "24h"
	GetUsageSummaryParamsWindowN5h      GetUsageSummaryParamsWindow = "5h"
	GetUsageSummaryParamsWindowToday    GetUsageSummaryParamsWindow = "today"
	GetUsageSummaryParamsWindowWeek     GetUsageSummaryParamsWindow = "week"
	GetUsageSummaryParamsWindowYear     GetUsageSummaryParamsWindow = "year"
)

// Valid indicates whether the value is a known member of the GetUsageSummaryParamsWindow enum.
func (e GetUsageSummaryParamsWindow) Valid() bool {
	switch e {
	case GetUsageSummaryParamsWindowLifetime:
		return true
	case GetUsageSummaryParamsWindowMonth:
		return true
	case GetUsageSummaryParamsWindowN24h:
		return true
	case GetUsageSummaryParamsWindowN5h:
		return true
	case GetUsageSummaryParamsWindowToday:
		return true
	case GetUsageSummaryParamsWindowWeek:
		return true
	case GetUsageSummaryParamsWindowYear:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageSummaryParamsGroupBy.
const (
	Actor   GetUsageSummaryParamsGroupBy = "actor"
	Machine GetUsageSummaryParamsGroupBy = "machine"
	Path    GetUsageSummaryParamsGroupBy = "path"
)

// Valid indicates whether the value is a known member of the GetUsageSummaryParamsGroupBy enum.
func (e GetUsageSummaryParamsGroupBy) Valid() bool {
	switch e {
	case Actor:
		return true
	case Machine:
		return true
	case Path:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`

	// Handle milestone-4 fix-round (handle-exposure): the owning agent's handle — my-task's own api-key-settings.tsx shows `{k.handle}` on every row and its revoke dialog names the agent by handle ("Revoke {handle}'s key?"); this endpoint (GET /api/bff/keys) already JOINs users for every row it returns (I21 — every key here belongs to a role='agent' user), so this is always present, never null.
	Handle string `json:"handle"`
	Id     string `json:"id"`
	Prefix string `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// UsageBreakdownRow defines model for UsageBreakdownRow.
type UsageBreakdownRow struct {
	Cost float64 `json:"cost"`

	// Key The dimension value to display: an actor name, a canonicalized path, or — group_by=machine, story-1/ticket-18 — the reporting machine's `hostname` (joined from `machines` on `usage_events.machine` = `machines.install_id`), not the raw `install_id`, falling back to the raw `install_id` itself if a machine has events but no corresponding `machines` row. group_by=path (story-2/ticket-7) is machine-prefixed: `<hostname>:<path>` once substituted, falling back to `<install_id>:<path>` the same way. Display shortening beyond this substitution (contract's "Console display rules", `path` basename/collision handling) is still the SPA's own job, not this endpoint's.
	Key string `json:"key"`

	// RawKey Present only when `key` has been substituted for a friendlier display value: group_by=machine (`key` becomes the hostname, raw_key the machine's `install_id`), or — story-2/ticket-7 — group_by=path (`key` becomes `<hostname>:<path>`, raw_key the ground-truth `<install_id>:<path>`). Carries the raw value so the console can still surface it, e.g. via a tooltip (contract's "machine label"/"Cross-machine path identity" rules — same "shortened label, full value still reachable" pattern in both cases). Absent for every other group_by, and for the no-machines-row fallback case, since `key` is already the raw value there.
	RawKey *string `json:"raw_key,omitempty"`
	Tokens int64   `json:"tokens"`
	Turns  int64   `json:"turns"`
}

// UsageScanRoot story-2/ticket-9: one row of GET /usage/scan-roots. Field names are snake_case verbatim from the contract's own API surface section, matching the rest of this usage domain's own break from this spec's otherwise-camelCase convention (see getUsageSummary's own doc comment for why).
type UsageScanRoot struct {
	// Hostname machines.hostname for this row's install_id, falling back to the raw install_id itself if no corresponding machines row exists (never a blank label).
	Hostname string `json:"hostname"`

	// InstallId The reporting install's raw install_id — always present, even when hostname had to fall back to it.
	InstallId string `json:"install_id"`

	// Name The operator-assigned label for this scan root (per-install, no shared/global naming registry across machines).
	Name string `json:"name"`

	// ScanRootPath The raw scan-root path, as configured in the collector's own scan_paths.
	ScanRootPath string `json:"scan_root_path"`
}

// UsageScanRootList defines model for UsageScanRootList.
type UsageScanRootList struct {
	// ScanRoots Every registered scan root across every reporting install.
	ScanRoots []UsageScanRoot `json:"scan_roots"`
}

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	// Breakdown Every distinct key for the requested group_by within the window, cost descending.
	Breakdown []UsageBreakdownRow `json:"breakdown"`

	// ReportingInstalls Distinct `machine`s with at least one event inside the selected window — not lifetime.
	ReportingInstalls int64       `json:"reporting_installs"`
	Totals            UsageTotals `json:"totals"`
}

// UsageTotals defines model for UsageTotals.
type UsageTotals struct {
	Cost   float64 `json:"cost"`
	Tokens int64   `json:"tokens"`
	Turns  int64   `json:"turns"`
}

// UsageWindowRow defines model for UsageWindowRow.
type UsageWindowRow struct {
	Cost   float64              `json:"cost"`
	Tokens int64                `json:"tokens"`
	Turns  int64                `json:"turns"`
	Window UsageWindowRowWindow `json:"window"`
}

// UsageWindowRowWindow defines model for UsageWindowRow.Window.
type UsageWindowRowWindow string

// UsageWindows defines model for UsageWindows.
type UsageWindows struct {
	Windows []UsageWindowRow `json:"windows"`
}

// User One row of GET /users. Every active user, either role — `role` rides along so a client could group/label by it.
type User struct {
	// Active Always `true` on every row this endpoint returns (`WHERE active = true` server-side) — present on the wire anyway so this schema doesn't silently drift from `Me`'s own `{handle, role, active}` shape if that ever changes.
	Active bool     `json:"active"`
	Handle string   `json:"handle"`
	Id     string   `json:"id"`
	Role   UserRole `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserList defines model for UserList.
type UserList struct {
	Users []User `json:"users"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetUsageSummaryParams defines parameters for GetUsageSummary.
type GetUsageSummaryParams struct {
	Window  GetUsageSummaryParamsWindow  `form:"window" json:"window"`
	GroupBy GetUsageSummaryParamsGroupBy `form:"group_by" json:"group_by"`

	// Machine story-2/ticket-10: optional install_id filter. When set, scopes `totals`/`breakdown`/`reporting_installs` to only events reported by this machine -- not just one panel's own dimension (contract's Console filters section: global, not per-panel). AND-composed with `window` and with `scan_root` when both are set. Absent means no machine constraint.
	Machine *string `form:"machine,omitempty" json:"machine,omitempty"`

	// ScanRoot story-2/ticket-10: optional composite `<install_id>:<scan_root_path>` filter -- same machine-prefix convention as `group_by=path`'s own cross-machine fix (ticket 7), for the identical reason: a bare scan-root path/name is ambiguous across machines since naming is per-install (contract's Data model). AND-composed with `window` and with `machine` when both are set. An invalid shape, or a well-formed but non-existent `install_id:scan_root_path` pair, yields an empty/zero result -- not a 400 -- mirroring this API's existing "no matching data" tolerance versus a malformed request.
	ScanRoot *string `form:"scan_root,omitempty" json:"scan_root,omitempty"`
}

// GetUsageSummaryParamsWindow defines parameters for GetUsageSummary.
type GetUsageSummaryParamsWindow string

// GetUsageSummaryParamsGroupBy defines parameters for GetUsageSummary.
type GetUsageSummaryParamsGroupBy string

// GetUsageWindowsParams defines parameters for GetUsageWindows.
type GetUsageWindowsParams struct {
	// Machine story-2/ticket-10 -- same optional install_id filter as getUsageSummary's own `machine` parameter.
	Machine *string `form:"machine,omitempty" json:"machine,omitempty"`

	// ScanRoot story-2/ticket-10 -- same optional `<install_id>:<scan_root_path>` filter as getUsageSummary's own `scan_root` parameter.
	ScanRoot *string `form:"scan_root,omitempty" json:"scan_root,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List every agent's non-revoked API keys (I21).
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke any agent's API key by id (I21).
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Session-check endpoint backing the SPA's AuthGate-equivalent hook.
	// (GET /me)
	GetMe(c *gin.Context)
	// GetUsageScanRoots Every registered scan root across every reporting install.
	// (GET /usage/scan-roots)
	GetUsageScanRoots(c *gin.Context)
	// GetUsageSummary Usage totals and one-dimension breakdown for a time window.
	// (GET /usage/summary)
	GetUsageSummary(c *gin.Context, params GetUsageSummaryParams)
	// GetUsageWindows Turns/tokens/cost for each of the fixed 5h/24h/today/week/month/year/lifetime windows.
	// (GET /usage/windows)
	GetUsageWindows(c *gin.Context, params GetUsageWindowsParams)
	// ListUsers List every active user, either role.
	// (GET /users)
	ListUsers(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// GetUsageScanRoots operation middleware
func (siw *ServerInterfaceWrapper) GetUsageScanRoots(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageScanRoots(c)
}

// GetUsageSummary operation middleware
func (siw *ServerInterfaceWrapper) GetUsageSummary(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageSummaryParams

	// ------------- Required query parameter "window" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "window", c.Request.URL.Query(), &params.Window, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter window: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "group_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "group_by", c.Request.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_by: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "machine" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "machine", c.Request.URL.Query(), &params.Machine, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter machine: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "scan_root" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scan_root", c.Request.URL.Query(), &params.ScanRoot, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scan_root: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageSummary(c, params)
}

// GetUsageWindows operation middleware
func (siw *ServerInterfaceWrapper) GetUsageWindows(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageWindowsParams

	// ------------- Optional query parameter "machine" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "machine", c.Request.URL.Query(), &params.Machine, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter machine: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "scan_root" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scan_root", c.Request.URL.Query(), &params.ScanRoot, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scan_root: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageWindows(c, params)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.GET(options.BaseURL+"/usage/summary", wrapper.GetUsageSummary)
	router.GET(options.BaseURL+"/usage/windows", wrapper.GetUsageWindows)
	router.GET(options.BaseURL+"/usage/scan-roots", wrapper.GetUsageScanRoots)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zHz9jhs3lu+rHNS9QEu5Jam705m500GwcGIn6Ywde20Hg8UocFFVRypGFFlDslrWJAb2IfYJ90kW55Cs",
	"Kn2l7Rl7sH9ZLbHIw/P5Ox/lX7PSbBqjUXuX3f6aWXSN0Q75j69F9RL/1qLz9FdptEfNH0XTKFkKL42e",
	"/eKMpu9cWeNG0Kf/a3GZ3Wb/Z9ZvPQu/utkTa43N3r17l2cVutLKhjbJbrPXNYINh8G9NEp4dCDSVxNX",
	"iwbBWLgXSlZ8MthW4TR7l2c/Gv+taXX16an8Sa+12WqQVU7ECPoEvhYe8K103sGi9SCdvvDga4RSKIX2",
	"wsHo7nP47//8LxALh7rEHLTx0KDdSOek0ePpXNNFftKi9bWx8u/4L7jMMzpcr3LAt420GK60tUavJtYo",
	"BIdMHJTGrCUy/U5sEIIsLK6ErRQ6B2YJ21qWNZQ1lmtYCqmwgtHdF+MpPIIF1uJeGgtlLfQKYWnNBnwt",
	"HTSiXIsVXjggnn7/+tlTKL578hpmBdxL3N6GVT+8ev4juNYuRYkg1FbsHAjttmgd3Fxe5aDxHi3rSiUt",
	"lh5GAool+rIuWAJQChLI0ihltsN1JKKt2IGAhTVbhxa0uJeroF2VQcd3plWvXjyKVD5qff2d8DjBv7Xy",
	"XijUHmpj1iAdbEkRfGs1ae7N5RVI7c3gwBxKJVH7iZMVBpm/y6MU2eAeNfLPuKNPjTUNWi+DIZYWhcfq",
	"EWvC0tiN8NltVhEZXm4wyzO/azC7zZy3Uq9IlYJM3Yc8UgtdKaT1+3qykQqdNxonN7CUbyeWbA1GYfkE",
	"3zbGtRbHt8wps9VSr0CsUPsLB2ER83Gzm3jh1pGPopGTNe4mDr2XeuWm3r0FV5utg+LX9TQ8964Ao4HE",
	"uwNLstMVSO/A4r1ZI1RSKLMCLTbo+HA+FRa7dOxonr0MS3+NG144WOPu3+bZ+MugXairxkjtYcSaJxo5",
	"WyyXszXu3BiEsiiqHfzw/O5HB60jlVsaO6BIerAYRD66u77ii4Zf17iDGi3CApXRKwdBFYzCry4Cd3jD",
	"cQ7OBFKkS+rdWHSofVJt3SpF2nJCZpL9xNHXjcWlfHvip3d5Ri6VzD27/Ss93i3uFCAf6NtQkX7uzjeL",
	"X7D0dFDQ2KcyhIh9rSUe0r/S48Y95KWi6r/rzhDWit0RwbznKUKClzuiAU9/XZoKTzKulsHdHv2wQefE",
	"Ch9mKW/drz+m9WB9oPDUlZ7hMeGi9PJ+SMXCGIVC79vvEfWkdg+T3smfl+fpsFO0/USX+9qiWFdmq1+a",
	"LRNXVZJ8hlAvBkQvhXKYHwnAHXgm0y7UwC3pdrNAS0etg0c8hguV3KDmCHUvVItkYJV0jRK7W4rMovTG",
	"snPIQVAMMFqWQlFshUb4msMd2evKmrZ5s9h9tRFlLTXm4Lyxu8nVzMtyjX5y9f+7QGCxMZYcFsTFFw6K",
	"2jhP5xQw+sVIjVWIcUVc4tiLFS2x7A3ek9pP408FfNUvm0rtvFDqjayKcYAIfKTYQjH4KYelUIpIWIhy",
	"Tbc+tYr8JKolyCWIRCvUwkEggIGKNlAaGyBfRRsOKLZmO+05Q/yCUWDLdWLLH8fksuIjk+BFsLqFYt5e",
	"Xn5eJq7wX3gbvqSNwhfElBLBtQvnpW894Y/Di8Wd+mud3YtYwOBkK3ZTeBzUgOKJ9cgBaYE7o6vgaLsz",
	"SXdGBLKsKClazbNvjHaEfaIiMcZ08yyHgk4rYCEc0qVmpVFKsvKx1Ui9Ym44L5U6gAy/mEWS5iDgXLgz",
	"Lt2K7ZuTOv8iRAUwWu1gW6OGYo27gqW6QNRDXnKYErC0Eok6tN2N2FZuj5QeRmGzBZYmhdMkwRwiTfzt",
	"QPH3FTaa06GW7NtY0KT9s95TYfbJWDEMmXjb+vr9FWU8hW+EtTLekKwmOA8XzKiM8i+FjrJMyFP6HHC6",
	"msK9FCDAG6O8bA7UJzFTiQWqeTabZ99Y49wkfc+3lxVqL/1ungX16pH1PIsai1XYIodlq1QikemxKMpa",
	"LBTOM9rOo9UgNSyMr6EUDh2B7gUrSg9VjK/RdkLIGUjRr3RlbRJ5bkKQhoyQDZB2y8FJMtMgMEYoARLt",
	"c4+2xzP67M0atdtz9lL7P9z0a6X2uArOnqHUe609BgZZd1Ye4kva7mwAe1UK/dIY/2Dw2jfEAw3/0y0Y",
	"jQwHzRIYRrKvn7lS6Ik1xrspfCtRVRGqCovgtFjjG2Ix3KNdCC83KTNiLUw6xTnHi7tODR2WREUOG+FJ",
	"aKsYlpynw9nD8OFQmY2QOu6woEg9yLxcgyX9RHLbSoeTUmxQfUPUlEZThGDX6BBhhT7wqt1shN3FDStT",
	"Qmk2m6Rm23o3DvLfj/PJpk9kFSnqpSVRIaUjTl446I35fMTr1wzi3VFYS0exiGKiPkpZ40IJvQ7WNj4H",
	"srtTTgORHhTElRfukDpO/g/APUXi4Mc7FtSiouvRdbu7Sj89RdRprhI5xH/hjZ0I5+Sq8yU9f0kvgfQS",
	"Rg3aSSSTYhTl9har2UqZhVCkrnQriyvpvN2BKMmbdfwcnySMdn9Du78hb3eGY2ILnXVENCYc6d5SrlqL",
	"Fbm0YAlKIQG5qHe8Oa13J84+TG56seW9Ih4RGFn5oJNISc4HoNzuJHfMhichh2TWIt24l0pkc8wyD5WL",
	"Lv5eKdW+i3sosxrQep4VwQd8IBcWKU04x4RKOi916TlnTmEpVv6w6sIWbKWvo15spa7MNgfy80B7Ipv6",
	"h/FmL3854g+xJ7L+TWT9CTE+TrQn7Fw4phOEB4WC3LLGALpJgLLCgFWR1BqreBH2DwQRlVyilxuki7xP",
	"uDReqPe77Ouw9FDscYd8IKWTFz+rE687Ej5N+vevgQ8fCBz+wlL7pGnvJ7p3ngWN4+KIbjd0+S/ICV7f",
	"1AygKkFAaou4zvJsYzR7yB0Km+VZ0s4BY8743nhIouwQmT3A2A9Vp23/1Ptbfy/Dh1xj2v401WiPvcLz",
	"IzyI1k0huLtQVuHqXw4oGZpzwZ2cQEGfCrCyIqCojF5RaiJi5RhK06roEWchqi92hBBOQK++VLRP26MA",
	"QwpvWzyor+5XRLvCZvGX75+8fJLo/grCkw7tPdpQy2bSmy4/jS7aIgi921IibhLyIAFwbV1feHBSofZq",
	"B5WVSx+rJs+wiMG+iFXbnNmTRwLeFbEDIZex9UJALjQX9nPq96uNnSmhppJZMhKz1Ug2wLXbhw0ggI4P",
	"KaihPV1GZd35ANWOHuH3FDpseaI0yWB3aU6Dtq+//fbCpa7QRLS+pjyhFBTG9po0o75j8DkU07KWuJwN",
	"vpu9SQnO7NGLu+mGqweUebcbrEJ5Y7FLRRSwrdYB/qQGA9oureG2TTKs1D8ckubABJwfoHAO33vfPKcj",
	"9ttbOeVQRt1jRWcX5C+tFmrmrdCOouFssVwmxUyPbmRVKdxSPjcqFsvl9GVgMnHjVVhTjLvYvtiROfi6",
	"u0xMxG4JeBcOy9ZKvyuCkSAl2xWWivB4aCQYDU1rG0NZeUJJ+FaUPhQPLApnNBSmQS0aOd2JjUoE1ygq",
	"MpKYsa3kPbq4h/CwlApv9xLDX8yCzo8MnaWuMHzGlvfZsAs7KlZST3pOpNIlCWEKjyhhNbrKQeoKG9QV",
	"Z4xSxT7gPrWDK8KoONISmGevt4ZpdOEQo3GejbvqbNMulCw5Xx59jcKi3VfTPHSIJktRcsFOpIrg199+",
	"22vvSQ3Pg+LFR7uGISnrmBN6v+Xy8y/sOhtrzHJilpNU64ENkoeSbuNID0jZvW3LwMG769nd1fU4lGVI",
	"U/VKYUzF+LaBYVv2/QvVRrEtTKsrYXchkfS1aVd1TJoqBNRLY0t0ITo8RiUXlBai2oUutB+WA8LVb0Md",
	"hySvDYNx6VwrdMmdd2t8kHgXIHjxiJT3xfNXr4GbZgWnkbw2hoWBcnKN+ZR+Fvzs7FdZvSv2tfQWBGeL",
	"RE3o4y4wRiZijljShYKJa/j+9esXkJSVG2vdBYi13Q2cFzv45undhH3NqU52V/VzINya6D6hjzkUe15t",
	"ZYSafff80VNW1sf0Laf3X4yncx2uWHA7cAuuETpleMWwKVgwLohsoSf6RkDyOskDju6urwKLeyquZ58P",
	"fHRQWVeahniFG0Ha7GAUdK+1QpE2BDyAm8bvUrmvE38IrsRF5MpEpDWQUORwdx20/+WTF08fffPkMetE",
	"IHmNjQ8IhrMeARq3ne5MoQigqOBrxPuGFv2kbcaguEqDDwOmeMfEG612OT88CR830lpjuQq0138uaLep",
	"505H69EGT6p2EUBIT9E/o2cIuLKDePTiLsuze7QuxMSr6eX0kmJt1OjsNvt8ejn9nJCY8DWH6llqgq7Q",
	"n0t/T8tfGz0Jfe6K9QBGRfzzjfBw9wp+/Onp0+Rsf2ndaR2hqybvuPdbbC3XRlUOBEtbkLgUnTOUcW91",
	"UQuMRpY72xfpVihCSpcKc2HqJbqrqF3BYpOSBRvbCnekuaL0rVCwaFdTeLlnl9yHDp29OK8yWbR+0uoB",
	"k1LJnscI2iYV9cOFuaSPCNKDRqxcdAd6NYUnoqwZAJeD3sDBJEMRwFyRKoe6VSooIPsQOlGQm1NxTuCH",
	"53c/Uhyo2hKrYEZcuo8lzuikUvt/SKRHpWBbUxCMRhj+WODSWAzDD0SZ0bHkHgp+0ui7KrvNCEX+mbQu",
	"35/mur68/GgzRYO2/4nBopjmRMYdKjKPbN1cXp07oyN6tjcOxaMyqf7El0ze4cQ5hACC0ZCPnPLDfYgJ",
	"hqjQn8iOXqF3MLC0Ygo/Gg/Rh/IMxzzr5rrMVs8zllI0si56ujaImuUUZB48FatLhzXIf3JtWPcXYaFX",
	"sBG7EOuYlLxz6isG3LTNFB5paLuRNDq5uLm8IY/wZkngoMj7xug8OzN8Ns9iPjVsFQ0jx2Sxm2jDd5ko",
	"XPqJN+EXUMas26a7YLpV69AR2/ZwAUfgDhr0IIIyxARvh7vkUA0xCzPpYyCB2RkUMCrKTTVjHzdZ464Y",
	"vx8uOGWBYeboz9yROjDBm2ONC6urf9Qs6KGbhx/qZiT37SiORw3VL9oOFxaqzoAoplmxQc/J6F9/zSTR",
	"Piyg34act88zvW0xHziUw4T5ZzLK0MQ4GR1fBeAYU4+go8IdAH3yzN3k1v3VbIPFCc3h/tz+TpT9zLNt",
	"bUBs4C6fZ78rb+FIRCdk/R36Z/gpXe0zPDcuGzLaiYwR/aP41Zi1TsIkZ2ekC1GuU68xDDacm4OMvvaw",
	"AXpWyMe9VG2gV7UwUBdadk1rSZ7eQGOaVpEXGbTsLxwsW99aHDSWllIRtKusaSrykaNwClxdjRPSHfrs",
	"optS6JohBXR1cWiERhV9FFFNQJvdoKgqBj8VWsKpRBQh0JBgdT3WAcygJNFB0bdcCsbW+/NCw2GelO73",
	"ExmdX6e9wPmdQigOerVd9p/ai3uDL6mTT94aRvQ5jjZYbAxs0Nemiqk8vPr3pwxocoobIfvkwxuLJVKK",
	"G6LYYBJqKZRy7z+h1DW/9hq/PNrywJQSjFxNSJMCgjZ2wzlNLZoGNWeQcTSCkpS2cWh9Gs/qOCj1Ch2z",
	"ZCF8Wec8GzWImyc6xXF04yzHu2bQLM4NdT2sbroisd8R4GD3gC5k1N6Y8RlXs9fS+6QI77j1eRboneph",
	"5g82MT+Cs/onWqhDJ9U3NX/HQ/XDgDe3B26HBM7mk4IFg5C9eb8CRsUbHvaZTaeztGNfUEgfppuq4EGi",
	"wcgH4bMw9ME2xmX15WCaJBQUSL8pF8PqaJ5E+G6gJAepS9WyGUkCuv0YStG7v2JWHHcAi5S27QVX9o7u",
	"uJQU2XJyrASVQ4Z8X7J3mWds3qXHap4FC+hcc0c4eeiQY7IULhwo6dEKBVI3rQ9+yhnyWhynDFiktHw8",
	"hSK0b4rYcw0A4q/OC8uPbcdg+b2EUcHNr2JWbBHXxazg5lcROEsBrhJ2InRZG1I14eGn19/ARlZarmo/",
	"e2Z0JXazK+e/hOKLupgV1zfxYWt4eGX85YDD0Mhy7RJHu0FWIq3oIg49bgVngGvccWV6CkXo2E5DQ60A",
	"124c5+1L01p2sqFiUZpWcwQljx36zyPmFfw/MK0PH0pR1viGlTf9wbPf0uiYl6RqZBofDA3KvO/ZB9GH",
	"uPon1t3gL8mseI7DG+C8lwNhcpxiYaKT/YysAavPiM5J0OvSqHajXVK4/a4Ug/WUTlcuzchb3FrpKe84",
	"pbtBfTAwhdBdddS2D5Ns/1DzfjTs3PfV6JUR6sIRmPFSqMm9xC2U4h6Fzwf5ZHhp5HCGqwOroSCidlCS",
	"V3HTuZ7rIp1VcA3FWLmSOtTywMm3vg53ySG0UO+xq8zsz5XxvC4sacGwunngjE5Mnw2PJCdUpeoZqf5v",
	"1zf1b2xKv5Eh/RbMKLBlqcRqRdbjKJ62UlX8NgpUWIZhWqmTLl3ddK6VxBmcbmf99MPGlJR9coE8DtbB",
	"vOtR82gI+c7g3sFLhUmjNImVWY3h+uk+UaIu9lnDa0YwYv2tA9GURFGoIf9B3qWXRZBQjDlBaUL1lPEF",
	"VtA2JAhttnnQMm2A8umw53SuDyLN9WVAlsUOhS1gdNIJ/SA0XMHl5e3lJTukeKuytZYIoEcHs4KnXVzn",
	"rOP+XWNh4LRTE0skdwaf/+GLSSV2kWWxexG8rtsT4jwbMEk6+FuLdjcJaeCkU9FQrtWRY1E0pJ8+DruW",
	"QqnbAOYiR+jAwdbka7XZchEuj0ZKz9IOLsRBoZyBilF6MRjUjFIvLgZmER4d0YaOGyzWbF3OFUTeqsNm",
	"IQDvF2L35rwDIkxRiG/fZzi/C/QiMjmde/NGffLdTVycT8A/7rzHaTJShHsvQvgVjVgup9ODKz5z2u/m",
	"jVeXt2CaMC4yTCBCBjiFv9SoCWpHz+tSGC1mg3B7EvaQyaaYo/ndM1oS2sQs6DTbPZn0GmB41lujSuOy",
	"XYQfzounlw0CkS5511sI45ddoW7CW42n8OjHxxMGyY6DD1lCUiuyhfDNIHfl7lOX/jj03Wj4BoXm1CpR",
	"HzqSQuo4S3JKtkk+v1fU+SBBhbtIjw8M8O9PbKZ3PmJ2P5mERG3/RZSh7xJukNpzPpY83t5wPj2VKgR/",
	"HPc99tDDLYWKXcxbCgNir9BAm844xZYOxGYhV61p3eG8bGquhalaydAsTd/uKcZj4QVsTPX+Qu9QzCmR",
	"U1jljn0ofYVXl2GLSk2WxlL4Dm8D6QlXWkg/Bon67T73C2iEtDnsCKo5bsdsGr+b/R0tgW7XKp9MQcDN",
	"5SX90Tfh2GJC2Y7Pou/mGethDFGV8GKegTcKLXduKagSL2EjVCQ3ziWc19SO5N/V1Z8/ef4cHfipAh67",
	"n5zfPU4Fpjj00k++dm4jj6MKafA19XQ7f9WpESPcmF1fPpxdD17x/wgJOV8agmdlio3GSe/7+puGt5MY",
	"poUL7WXkg3G+983IF4LSqf28nLafRIgeonlXCjZbTotCpE+zxIzy6Mr8AtXwjbLzdZ5kiV2AThu48KIy",
	"ZZY92hvkfwFT8ivEMbN1aO8lZ87bmqJCX7Xoc+rI2m5yJ5HO2W+jJA8ZdQwfn8KU/OrXNqbsDH75T28i",
	"zOE63j+Ar0YB+rGR74G/DpDTRcWCuy2TgMZTZc2LRQR4oR/K/iu8N91NSg1RmTeGeUCyZodV7mCBfov8",
	"QoUgF1oqWa55MTvJ8KWixT3S3gtKKyG166Xut6aPU305by+8prh9pB1dca8WrmvwDi/AOJRMigsS4WVV",
	"EkW5hwjSG5dX4GrZcL64lwqzWrHfZfVzY46FRwD1uCY5uEOvuJUp3eFcWRoZyQdBsH/V6zRqTSO8R6j1",
	"AVzQBfLzOI4i+en3kfoA2CPrT4pijqn9JyDM+WudktT0f3fQS/I/EfSen/W9UsMXdQ7XN3UOnJPkQClJ",
	"DpyR5DGP7VyJsdVHani9bq12s1BMm/HbJPzWJBeslgO7/aKeXd/UM6ZtRqTNmLIZETbr6IqRq4tmcXL3",
	"ZBR7xqDIPTSXNCrIaxUxPz41ig3PXz5+8hK+/o/4314UOcyzut0QwueJwhUnLlJz7KPd5tl4CjxCQbty",
	"yy38lw88vNc2VfoYpiQO/vuOSFjozaRCinEYR7M6rNL11eJkqjeAb0vECqSfwvMTc1vB88pgEcNxhEH1",
	"b6/M/CX7Tv5fP2KraNE6gtrkJdsNuye9ihM5oyFNg7blqaHZwSRpGIsanxu1+YmF/EmNKk6Gn5+0Gc7H",
	"sWmE9DSow0eftzkzjTcNBIbXAoLHb63KbrP0n6pk735+9z8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
