// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	Id        string    `json:"id"`
	Prefix    string    `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// IngestUsageEventsBatchRequest defines model for IngestUsageEventsBatchRequest.
type IngestUsageEventsBatchRequest struct {
	Events    []UsageEventInput `json:"events"`
	Hostname  string            `json:"hostname"`
	InstallId string            `json:"install_id"`
}

// IngestUsageEventsBatchResponse defines model for IngestUsageEventsBatchResponse.
type IngestUsageEventsBatchResponse struct {
	// Inserted How many were newly written. `received - inserted` is exactly how many ids this batch named were already ingested by a prior call — an idempotent resend reports `inserted: 0`.
	Inserted int64 `json:"inserted"`

	// Received How many events this batch named, duplicates included.
	Received int64 `json:"received"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// UsageEventInput story-1/ticket-11 — one turn's reported usage (contract's Data model: one row per unique `message.id` carrying a `usage` dict, never one per JSONL line — ticket 9). Field names match the contract's own wire shape verbatim (snake_case — the underlying `usage` dict's own key names), not this surface's usual camelCase convention (`assigneeId`, `dueDate`) — a deliberate exception, since the contract fixes this exact shape and ticket 12's future collector must match it. No `cost`/`source` properties exist here at all, and `additionalProperties: false` — the server computes both itself and never accepts either from the client (see this path's own description).
type UsageEventInput struct {
	// Actor Which crew-home produced this session (contract: derived from a `.typ-crews/<name>`-equivalent launch-directory pattern) — a domain fact about the reported session, not an identity claim about the caller of this endpoint (I1 governs the latter only; this field is nested inside `events`, not a top-level request field, so `RejectActorFields` — which only inspects top-level body keys — never sees it).
	Actor                    string `json:"actor"`
	CacheCreationInputTokens int64  `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64  `json:"cache_read_input_tokens"`

	// Id The idempotency key — `message.id` (ticket 9), never the source JSONL record's own `uuid`.
	Id          string `json:"id"`
	InputTokens int64  `json:"input_tokens"`

	// Machine The reporting collector's own install_id (UUID).
	Machine      string `json:"machine"`
	Model        string `json:"model"`
	OutputTokens int64  `json:"output_tokens"`
	Path         string `json:"path"`
	SessionId    string `json:"session_id"`

	// Timestamp When the turn actually happened, per the collector's own transcript read — stored as `created_at`. Deliberately client-supplied (unlike `cost`/`source`): the collector reports usage after the fact, sometimes with a real delay, so "when this was ingested" would be the wrong value here.
	Timestamp time.Time `json:"timestamp"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// IngestUsageEventsBatchJSONRequestBody defines body for IngestUsageEventsBatch for application/json ContentType.
type IngestUsageEventsBatchJSONRequestBody = IngestUsageEventsBatchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List the caller's own non-revoked API keys.
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke one of the caller's own API keys.
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Return the authenticated actor's own identity.
	// (GET /me)
	GetMe(c *gin.Context)
	// IngestUsageEventsBatch Ingest a batch of usage events reported by a collector install.
	// (POST /usage-events/batch)
	IngestUsageEventsBatch(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// IngestUsageEventsBatch operation middleware
func (siw *ServerInterfaceWrapper) IngestUsageEventsBatch(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestUsageEventsBatch(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/usage-events/batch", wrapper.IngestUsageEventsBatch)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFnbchs30n6Vrvn/KlEpHqTY2apwr+TY2WXiU1n25iJKaSCgyUGEASYAhvSsS1X7EPuE+yRb3cDwII5s",
	"J+XslWlqBujj119//FBIVzfOoo2hmH8oPIbG2YD8nydCvcHfWgyR/iedjWj5o2gao6WI2tnZr8FZ+i7I",
	"CmtBn/7f47KYF/832x09S38Ns2feO1/c3d2NC4VBet3QIcW8eFsh+HQZrLUzImIA0X81CZVoEJyHtTBa",
	"8c3gW4PT4m5cvHTxe9da9edb+c7eWrexoNWYjBH0CWIlIuB7HWKAmzaCDvYkQqwQpDAG/UmA0eIR/Odf",
	"/wZxE9BKHIN1ERr0tQ5BO3s6vbLkyDsr2lg5r/+J/wNnXtDldjWGWpil8zWqMeD7Rnv64HHtbunDxju7",
	"mnhnkF3WVsio1zhpA3qQHhXaqIVh94KoEVKqPK6EVwZDALeETaVlBbJCeQtLoQ0qGC2+SW7fjbMjXHMX",
	"jf4RO/rUeNegjzrVovQoIqoLDgZZK2IxL5SIOIm6xmJcxK7BYl6E6LVdUTSTL+H3vKI57EdfNx6X+v3A",
	"n+7GBVUohayY/0yvbx8e75m8b8sv22vdza8oI52fnH6uU6MdOn6LHf+rI9bhU7nO0bvb3iG8F92RnXzm",
	"kCGpVo5swOGvpVM4GK9Kp6I9+kONIYgVfjqSfPTu+WNb7z2fLBxyaWFXGOI7OubZmoL1RERZ7eGaUEpT",
	"Rwjzes+7pTABx/fjsO5x8rOysbt0YZs2HqdlXFQuRCvq4TBqG6Iw5nqwKu+X3u7ZvVPHvcm/JzJpAhyn",
	"W9uAPiZkOkSSv7sN1MJ2sEGPYHFjOth4HSPaKZQeJeo1KphAf0QJOgC+FzKaDqr+ba0CxEoHuCFDgDxQ",
	"6UhhPArVgWaTUcFNBwIar51nkE3gSmiMdeMIM8FjQKvAY+N8DFD2V8/hrCTcGe8gQdv4l8c7ONA24gp9",
	"wRFOpn/E5RTgI7vHoNqE2BhAW2lahWr6ObfeS+zWhPEuAUPZfDGQsQTVe8Vz45xBwbOmElaZ4bojsP90",
	"xeUD8uPj/rIh2+43wqe67jDUITrfTc5nUctbjJPzc862swix9fYk5ByjgpbugRGNTS9kPAnwVEQBtVNo",
	"5vyGdxuau9Ba/VuLUGaAmWpVghTed9quQEDJJ5WgtIxjsLhGz6/Tqz9cvnr5HIy2yHYkq+Db0yl8r9Eo",
	"Tn+AmkuBScDOGqIOG+37GblGfyOirmEUrLjFaylCPrNCaK1Cb9iefWvyKbfYpYtOE5fg8gutXwqJJwHa",
	"0AoDUtRovqNDpbMUfWJNo1KEoFcWcaHKMZSqxaciYnmaeggUGn2DXkQEfC+RkzCGoK3EA3dgqd9jrnvu",
	"5OyUsKqPyfnXJwGWbWw9vWYMyug81G2IOTw6TuGlg1K6EMtZGVzrJZawK+JEq6BiDIggjBnzBeVQ+cyB",
	"y6fchjCgp8QRMrfUhjcu0p0BzZJPSXkVkrwMgDpW6GHpXZ0cNZpwZBQQk5eNiFUO/16BniYwOWq8NDAP",
	"K/mnRIM8biaVq5EcVa1EldOHTAZ39TsHhZ6Rk40SUE5j10zo/TC7as/OHkmqAf6E5YR6cy0MGW1Ea2U1",
	"UdpzzDuyPaK32yS7WmgLS0qbuHFtoqvbPsqWpNJKsGqjjh1II3S990YiuMTwUh1Y1ThNQVucw8qt0dvA",
	"zxm+Hpw13V/To0vuFR3AJkDXNmiFUCY4LfPVEF0zMbhGs10O+MUxBAflGySAuSAPufVCSn0im3QXndqg",
	"JHjennPjVEftE/jZVAIBCaRjTuURHkohK7xmOqedvdaEYdfR3aINB9Ty4TmSTqAZ9kfe1gPzh/al7bST",
	"7BE7dIBooy049SDGbcFtlnHMo3Re5bIu21ar8oEo/AHDayErbXHY+lRthG9bbMhm7LgMjN69Wzw9nQ7Z",
	"w6g+OL9cG3+3qdTcg4flXrh+YDWgTSJEUTdD3Y6WA05jCoSMrTBEd0TToCWG0OSE3Pc/emHTQUAlk1ar",
	"6DwqEAHKvFdci1hO4ekWrk2XIWsSWloWacdqrdG3eB9gT+eH125JUpqfYhmzYYQP1Go1spuw0bHipVwY",
	"mhOi4z68KjbJUx1gI8KWpF0VsHGtUXCTJgdvkrTAt8iIfo+FfWQxG1qz9vIyznibs7iru75I7hXv/Qp5",
	"uD8/3vv72R/YULhnlm64+iPWjRGRhjURizfPLt/28xtG5XU/AmYXrxfTWpWnU3i2Rt9tYVC0sSJQTgST",
	"oBbKiywesKlzeILCo4c0KHabeh4XPWUuRaOvCQ9LIkfEpsSG0STpG5eXryY6hBYV/PDTW37JY3BmnUh4",
	"SS3krTCzfkaUJwE4HRN+rmXSUWulDG6Ez9IH0XfbxYq6X+fSIaSeg3VQBpStp6OANymkMaFQGkEdwFzA",
	"WWha37iAPTV51aC9eL3IIH9V6MDT4xYtNLwKxKsiCRAhV2We91uaTg4v9apKk2078mqnWoO5Mxfns8XX",
	"s8U3rD0FGJVTWWlczmptMERncXI+2+Vu8fIfF28WFy/fXuYUvu39PAnwq7shv3I+Z73wBl8xjfpqX+ga",
	"lSttJ7sYlpn0UQ1ksNaRKHtRd5Pk88XrRTEu1uhDKrnz6dn0jLGxQSsaXcyLR9Oz6aPcM4ySs15qWGE8",
	"LtrnrG8dqFoUEevsJGtFaaqOyvzfaxFhcQkv3z1/TgYfCkKsh3R9DWbVaXLTxklr946DELUxECq3CdA2",
	"hDZ7tEMKS6MbdASLqAJ4FwVPlNHiWwrujqhQqBhcUg3skWajA7+iUOqw43PE5jj6C5Wd/5GiMz5USL8+",
	"O/tiOt2eCPSAPvrRwLMS+vjs/KFrtnbPDlRGlt/auha+y35+PMcXrxf9dXfjVDKzD1rdpYIxGAem/SXS",
	"Ar4ri3IKrzYW/SRI19AgZN3w8dljbiuacchY57hB3d6jjD3MXpw92HlgtHjEDUbowHCxNxYJU16/unwL",
	"M9Ho2fp8luCOio+gTRB+6ADfPV9MmDWOSlmrGaPe5Ba7crAk3rA7P2J3XBOPj0OQnlZ/NEn00uNPv7QV",
	"wg+zmi7nOcNM/V5691JKaOBFjRF9KOY/fyg0GZ+natKp0vTdjePoWxzvlfj90f0LlUkSuAZxpayR1SAy",
	"i6O/ETQc0gwBj0v0RN/7vS3vdinL1u1WDlbho7jFAMKmyhGZU2k1lMC/YXyBf2ZDv8CHGnl/eKtk5hdp",
	"3zfIVDMOX9Gz6zzZcgcz55uktWvGAhbrSC4M5OpIiTkJIB3lgikfzao+H1NY7LQ4Z6HkfeRgO9lXT06o",
	"ZVXbUCGO73dv/Ky15XTO1JRVP7fMv80cCYeyEvSRTiX2Mc3cOKkKvQAhWMXciQP9Br4nCyQ1Iq1c9+St",
	"EirBtbmnYyyd7wnHJ/ULJtWiv4jrmpziFqlhRWAqoNzxg2sWv0vwgs+PlbBQiTUNNTI4Ee6gDdpoup1H",
	"ZIdeWcc/97Aek944EJIovCu06IXZF5HIHQEhetFllWXCrIc2CpVWdAbjIwkmR3tEhmWxofFa8s3ixuAp",
	"myXMRnQBAs+NlJQ5XBXSiFbhtXQKr4oyI8JQaw8r2xm2MMQnTnVfrM0//gPD3eHyQmh5d4Q553+6MVnT",
	"fwCPkm5Nu1vjncQQMC2d5U6vr0VHexzzN66wraxfAq9/tCWygv95gv3oSKrvfwR9nCD44yC499P0F8DN",
	"FDUQORBumTfhrO1vdTF2Yrc2Z51imsKaSj2NzdabYl5kulHc/XL33wAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
