// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	Id        string    `json:"id"`
	Prefix    string    `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// IngestUsageEventsBatchRequest defines model for IngestUsageEventsBatchRequest.
type IngestUsageEventsBatchRequest struct {
	Events    []UsageEventInput `json:"events"`
	Hostname  string            `json:"hostname"`
	InstallId string            `json:"install_id"`

	// ScanRoots story-2/ticket-8 — every scan root this batch's events were attributed to, upserted into `scan_roots` once per batch.
	ScanRoots []ScanRootInput `json:"scan_roots"`
}

// IngestUsageEventsBatchResponse defines model for IngestUsageEventsBatchResponse.
type IngestUsageEventsBatchResponse struct {
	// Inserted How many were newly written. `received - inserted` is exactly how many ids this batch named were already ingested by a prior call — an idempotent resend reports `inserted: 0`.
	Inserted int64 `json:"inserted"`

	// Received How many events this batch named, duplicates included.
	Received int64 `json:"received"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// ScanRootInput story-2/ticket-8 — one entry of the batch's own scan_roots array, upserted into the `scan_roots` table the same way `install_id`/ `hostname` are already upserted into `machines` — once per batch, not once per event.
type ScanRootInput struct {
	// Name The operator-assigned label for this scan root (e.g. "main") — per-install, no shared/global naming registry across machines.
	Name string `json:"name"`

	// Path The scan root's own resolved path (the collector's configured ScanPath.Path, after expandHome) — the same value each of this batch's events carries in its own `scan_root` field.
	Path string `json:"path"`

	// SourceType A declared category at config time (defaults to "claude_code" if the collector's own config omitted it) — distinct from each event's own `source` (a fixed, server- stamped fact), kept as two differently-named concepts on purpose.
	SourceType string `json:"source_type"`
}

// UsageEventInput story-1/ticket-11 — one turn's reported usage (contract's Data model: one row per unique `message.id` carrying a `usage` dict, never one per JSONL line — ticket 9). Field names match the contract's own wire shape verbatim (snake_case — the underlying `usage` dict's own key names), not this surface's usual camelCase convention (`assigneeId`, `dueDate`) — a deliberate exception, since the contract fixes this exact shape and ticket 12's future collector must match it. No `cost`/`source` properties exist here at all, and `additionalProperties: false` — the server computes both itself and never accepts either from the client (see this path's own description).
type UsageEventInput struct {
	// Actor Which crew-home produced this session (contract: derived from a `.typ-crews/<name>`-equivalent launch-directory pattern) — a domain fact about the reported session, not an identity claim about the caller of this endpoint (I1 governs the latter only; this field is nested inside `events`, not a top-level request field, so `RejectActorFields` — which only inspects top-level body keys — never sees it).
	Actor                    string `json:"actor"`
	CacheCreationInputTokens int64  `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64  `json:"cache_read_input_tokens"`

	// Id The idempotency key — `message.id` (ticket 9), never the source JSONL record's own `uuid`.
	Id          string `json:"id"`
	InputTokens int64  `json:"input_tokens"`

	// Machine The reporting collector's own install_id (UUID).
	Machine      string `json:"machine"`
	Model        string `json:"model"`
	OutputTokens int64  `json:"output_tokens"`
	Path         string `json:"path"`

	// ScanRoot story-2/ticket-8 — the raw, resolved scan-root path (the collector's own configured ScanPath.Path, after expandHome) the reporting transcript file was found under. Distinct from `path`, which is git-rooted from touched files (ticket 13), not the transcript's own location.
	ScanRoot  string `json:"scan_root"`
	SessionId string `json:"session_id"`

	// Timestamp When the turn actually happened, per the collector's own transcript read — stored as `created_at`. Deliberately client-supplied (unlike `cost`/`source`): the collector reports usage after the fact, sometimes with a real delay, so "when this was ingested" would be the wrong value here.
	Timestamp time.Time `json:"timestamp"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// IngestUsageEventsBatchJSONRequestBody defines body for IngestUsageEventsBatch for application/json ContentType.
type IngestUsageEventsBatchJSONRequestBody = IngestUsageEventsBatchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List the caller's own non-revoked API keys.
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke one of the caller's own API keys.
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Return the authenticated actor's own identity.
	// (GET /me)
	GetMe(c *gin.Context)
	// IngestUsageEventsBatch Ingest a batch of usage events reported by a collector install.
	// (POST /usage-events/batch)
	IngestUsageEventsBatch(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// IngestUsageEventsBatch operation middleware
func (siw *ServerInterfaceWrapper) IngestUsageEventsBatch(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestUsageEventsBatch(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/usage-events/batch", wrapper.IngestUsageEventsBatch)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFrvcts4kn+VLt5VWd6iJHuSvbrVffJsZm+1k0lScXL7YT1lQkRLxBgEOAAohTflqnuIe8J7kqtugBIl",
	"0YlnKrNfEkomgP7761839EtW2rqxBk3w2eKXzKFvrPHIH74V8j3+3KIP9Km0JqDhR9E0WpUiKGvmP3lr",
	"6DtfVlgLevpXh+tskf3L/LD1PP7Vz79zzrrs8fExzyT60qmGNskW2YcKwcXDYKusFgE9iP6rqa9Eg2Ad",
	"bIVWkk8G12qcZY959saGv9jWyN9fyo/mwdidASVzEkbQE4RKBMBPygcPqzaA8uYiQKgQSqE1ugsPk+UL",
	"+L//+V8QK4+mxByMDdCgq5X3yprL2Z0hRT4a0YbKOvXf+E9Q5gc63GxyqIVeW1ejzAE/NcrRg8OtfaCH",
	"nbNmM3VWI6usjCiD2uK09eigdCjRBCU0q+dFjRBd5XAjnNToPdg17CpVVlBWWD7AWiiNEibLP0a1H/Ok",
	"CMfcTaO+x46eGmcbdEHFWCwdioDyho1B0oqQLTIpAk6DqjHLs9A1mC0yH5wyG7Jm1MX/miWKzX72deNw",
	"rT6N/OkxzyhCyWTZ4h+0fP9yPhB5KMuP+2Pt6icsA+0flX6tYqIdK/6AHf+vAtb+S75O1nvcnyGcE92Z",
	"nLznmCAxVs5kwPGvSytx1F6VikF79ocavRcb/LIleevD++eynrwfJRxTaWk26MNH2ua7LRnrWxHKaoBr",
	"QkpFGSH0u4F2a6E95qd22PY4+SxvHA5dmqYN527Js8r6YEQ9bkZlfBBa3z8Rlb4U5t5ZGyU6zm0frOum",
	"38yDKh8wTP+d0xO36DqgZUDLIFTKw4rMceEh6gY7dAgiBKdWbUAJwebQNh4dfVAmWCgO5xZgTYkEZHEb",
	"yuf8eba5LYV5b+1TljlNrIMlBjY7MkHee+fXBEEsdueRrUzU+Nywf7U7qIXpoqEM7nQHO6dCQDODwmGJ",
	"aosSptBvUYDygJ9EGXQHVb9aST8wP5A6MtleOxSyA8Uio4RVBwIap6zjehLrCBUerBtL5QEcejQSHDbW",
	"BQ9Ff/QCrorokj36KRP+7eUB+ZQJuEGXsbmj6J9ROYXIqdw5yDYWJ/SgTKlbiXL2nFNPvLwXIT84YMyb",
	"P4x4LFalQZ6srNUouKxWwkg9nmJU176MRmmD9HreHzYm23FcfwlenpG01iCgCa6jOkqkok9Y4iGH+AdO",
	"nNNcpfeP8jWIlUb+mmv1TnQcLim5ijkUfXYVIAbReAIBtSgrZdAXScQhCERys/+OgyZG4bHHetg754H0",
	"lgjWTYX3amNQghYr1LC2LgbfAcImONvM4C6rhTJ32SWL06CbJp1IFiIkDuV8o+1KaApZZTbET5Qnq4rS",
	"We+h1yhKes4ARKjGhd3Lklzi0FtNEEBLYMI00GqNZbDEBEtr1mrTOpRAofJOhGpG/+Qg1oHM9akRRv7V",
	"1hiV2btqK3SLgKKsYiCcQ3cpnFOcgqBCFObg+wLWCrV8Qj1vW1fiffz+VMsbkFhqsiFQjm8sWS0kTYCo",
	"FEwkrkWrCRws3GWlFq3EeyridxmoGLdDK5Bsab2tCTwlqBAVlsoHZcoAa2frqC/rd9FrxKIWMBGwVp8I",
	"fTy6Lbop+CDqBiWsRRkuc3jAJoDwEHYWpFqv0aEJuptGrC0pQBsyk4GmdY31OGqbEyTgOMizvvwMzDYG",
	"BqcE4LfAwXUPB9fXezwIrTMXPgE+SmjpHJhQu+BESaZ6JYKA2krUC17h7I6zsTXq5xahSMRqpmTBcdNR",
	"TggoeKcCpCpDDoYIAy+npX+7ffvmNWhlMAYmSwV/upzBXyiyuBZQHlFdiP7eS0OO2ynX9wZbdCsRVA0T",
	"b8QD3pfC4z7YWyPRaZZnKE3a5QG7eNBlhJkIB61bixIvPLS+FRpKUaP+M21aWkPWp25xUiQ0waUscihk",
	"i69EwCJGnQCJWq0IdxDwE4WGsiYHrwjHhupw1KUiyGU9KSWM7G1y/c2Fh3UbWjeIeqhbH5J5VJjBGwtF",
	"aX0o5vuQPuBjbCehimQMGMnogGIsfBbA4VMc8IITAoh1tVSTVzbQmR71mneJfhVlTABUoUIX040V1YpI",
	"xcQjRi0p5pP5BwF6OYbpgjQ9R5C/x/bP4W5a2RpJUdmWxC7ZfchN8CF+FyDRMY1ioQQUs9A1U1rv53ft",
	"1dWLkmKAn7CYUnpuhSahtWhNWU2lcmzzjmQP6MzeyZYKBSMEiJVtY5u+z6MkSQytyLFMUKGDUgtVD1bE",
	"xn4PxGhkYxUZbXkNG7tFZzy/p/l4sEZ3/xFfZRQmSmgiu1PGK4lQRAwv0tEQbDPVuEW9H4rwwhy8heI9",
	"EsDckIaceqkMxyabzqJdGywZjvt9VlZ2lD6e340h4JHKRbh8oiqUoqzwnttYZc29Igy7D/YBjT9qqZ8m",
	"lXEHohC/ZbWS4yV3T31L1ogVOkK0yR6cehDjtOA0SzjmsLRO9kWlbZUsnrDCbxA8kYlx6WO0Eb6dVsQD",
	"EYPJx4/LV5ezMXkY1UfJrG3Drxa1JzZPd5fPbC45kcQuPxAg2mHKLG2cCh1IwPPoUDgyXnDCRKFgrTRR",
	"WQ9r2xoZK8gMXh0RiYJkKPKUJMrDRgUWrkeZYNuyog9Ko99H0PWLfaHBwZFJem3jRO4pVhXh5Kn+nZgT",
	"c5YxwEQTj2ydAVGGVmhqH0XToCHO06SYPrXnwCqUdXEqFyzZV3go0kjqXoRiBq/2FU93CfWnvm0arVDC",
	"pDVaPeBpjbpcHB+7bzojBYlOozcIYgmtamQ1YadCxfNcoanUUqviiSruoqbKswP7pvcug51ttYRVLL48",
	"hEwUmIriSVf7mZne2IRu4Jc8lay8Z3Z96vZ5NkyEEyw4Tbin4e7zUDqMhJFBF0PQ2o6DScC60SIQ9yGe",
	"9v672w89HYJJcd9X1PnNu+WslsXlDL7jIVBfVUQbKqpxsXmnygXFTZpBs6gL+BaFQwex7h4Gvqn69uOI",
	"QjTqnspLQVyTyKnYMTjHMfnt7dup8r5FCX/7+wdetMeJFfegVKaFnvclt7jwwK6Z8nstc7haSalxJ1ya",
	"oK86EKYLFeGBSmFEhW9BbV/hsWwdbQU8dELK+n0nw9TqwP17pve2QXPzbplq5l2mPBfjBzTQ8Jgl3GVx",
	"ju1ThCb6tB+BkMJrtakiZOwZRG1lqzFl6fJ6vvxmvvwjX2F4mBSzslK4nteEPcEanF7PD75bvvmvm/fL",
	"mzcfbpMLP/R6Xnj4ya5Ir+TPeX9/A39gVvqH4X3JpNgoMz3YsEjQRjGQEEwFTbFXd9Oo8827ZZZnW3Q+",
	"htz17Gp2xaWmQSMalS2yF7Or2YuUP1x05v3EeoMjteM1X5McXY6QRYw103TlEEnKpEgf70WA5S28+fj6",
	"NQl8fK/AY/Wuj8F0eTFdtWHamsF24IPSGnxldx7ahpBnwOKogSeyqwIYROnB2SC4xkyWfyLjHngfmYqB",
	"JsbAoAfRXG02FGDKH+hxHGUoa5YyKf89WSc/vmj75urqq133DO4Snrhm+6zh+ULt5dX1U8fs5Z4fXVbx",
	"LU5b18J1Sc/P+/jm3bI/7jGPITP/RcnHGDAawwh5usXgYRAWxQze7gy6qS9tw4MAUSO8vHrJaUX1Lg68",
	"LSeoHbzK2MNk0JqjFhImyxecYIQODBeDEkmY8u7t7QeYi0bNt9fzCHcUfARtgvBDefjz6+WUSfikKGs5",
	"Z9SbPmBXjIbEe1bne+zOY+LluQni2/K3OokWvfzyov196rFX4+FcZ9Io8si9A5cSGjhRY0Dns8U/fskU",
	"CT+cnSxiJT6U5uBazAchflrGf6QwiQPDUVwpauRJO4nF1t8JKg6xhoDDNToeTqU2ODHW6GVjDx0cX+YG",
	"8YAehImRIxK/UnLMgf+J4Qf8PRP6B3wqkYfFW0Yxv0r6vkemnWH8iL5ZSZUtZTDzv2nsYuc8mOQZvfVP",
	"9g+DwRbPRckXTP+oVvX+mMHycM9hDRTc3h01e8Nh1AWlrGwbCsT8NHvDs7rAywXTVL5Rset0xX92KVNW",
	"gh5pV2Ifs8ST45Cmn+cIviE6zFr2rcZhyhKHO7GDPZkWFlAJjs3BWGhtXU84vjgOYoIt+oM4rkkpTpEa",
	"NgSmAooDP7jnO9QCnOD9QyUMVGLLvVbVz5+90jxFPWhEcqiNsfyrAR5vxRVHczky7wYNOqGHMzlSR4AP",
	"TnT9FJdZD3UXMg2s4cPIRCtZm1vKNLtpnCr5ZLHSeMliCb0TnQfPdSM6ZXE6nS4SIoyl9vitYYIt9OFb",
	"K7uvluafv6d+PG5kCC0fzzDn+ncXJt2XPoFH8U6Q+rjG2RK9x9iAFoe70Fp01NMxf+MI21+ZFsCtIHWM",
	"fDv6vMvQydk1aP9bmpcRgj8PgoNfOH0F3IxWA5EMYdepK073M/sxIytxaKHT2GcWzRpDPZbN1ulskSW6",
	"kT3++Pj/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
