// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machines.sql

package db

import (
	"context"
	"time"
)

const listMachines = `-- name: ListMachines :many
SELECT install_id, hostname FROM machines
`

type ListMachinesRow struct {
	InstallID string `json:"install_id"`
	Hostname  string `json:"hostname"`
}

// Every known machine's install_id -> hostname mapping -- the "By
// machine" breakdown's own label lookup (internal/domain/usage/
// service.go's Summary, when group_by=machine substitutes each
// breakdown row's raw install_id key for machines.hostname). The join
// against usage_events.machine happens in Go over this result
// (Service.Summary), not as a SQL JOIN here: Aggregate (summary.go) is
// the existing pure function that already builds the breakdown keyed by
// the raw install_id, so a hostname-substitution pass over its output
// reuses that logic instead of re-deriving group_by/window aggregation
// in SQL.
func (q *Queries) ListMachines(ctx context.Context) ([]ListMachinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachinesRow
	for rows.Next() {
		var i ListMachinesRow
		if err := rows.Scan(&i.InstallID, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMachine = `-- name: UpsertMachine :exec
INSERT OR REPLACE INTO machines (install_id, hostname, last_seen_at)
VALUES (?, ?, ?)
`

type UpsertMachineParams struct {
	InstallID  string    `json:"install_id"`
	Hostname   string    `json:"hostname"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

// story-1/ticket-18: the reporting collector's own (install_id, hostname)
// pair, refreshed on every ingestion batch
// (internal/domain/usage/service.go's UpsertMachine, called from
// internal/transport/publicapi/usage_handler.go's
// IngestUsageEventsBatch) so a renamed machine's console label catches up
// rather than staying stuck on whatever hostname it was first seen with
// (contract's Data model: `machines`). INSERT OR REPLACE, not
// usage_events.sql's own INSERT OR IGNORE -- that table's row is meant
// to change on every call (the opposite of usage_events' write-once
// idempotency), and REPLACE gives that for free on a install_id conflict
// since every column is supplied on every call (no partial-update case
// this query ever needs). Deliberately not
// "ON CONFLICT(install_id) DO UPDATE SET ..." -- that form's own
// "DO UPDATE SET" false-positives internal/dbquery/tableisolation.go's
// table scanner (it reads the SET clause's target list as if it named a
// table called "set"; see that file's own doc comment on why its scanner
// deliberately doesn't try to handle every SQL form rather than widen
// itself further). INSERT OR REPLACE has no such clause and sidesteps
// the false positive entirely, while remaining functionally equivalent
// for this query's own all-columns-every-time shape.
//
// Note: this file must stay plain ASCII -- bin/sqlc v1.31.1 corrupts its
// own star-expansion byte offsets on any non-ASCII byte in a
// db/queries/*.sql file (internal/db_queries_ascii_test.go's own doc
// comment has the full history). No em dashes, no Thai, no "section" /
// other non-ASCII punctuation in this file.
func (q *Queries) UpsertMachine(ctx context.Context, arg UpsertMachineParams) error {
	_, err := q.db.ExecContext(ctx, upsertMachine, arg.InstallID, arg.Hostname, arg.LastSeenAt)
	return err
}
