// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	KeyHash   string       `json:"key_hash"`
	KeyPrefix string       `json:"key_prefix"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type UsageEvent struct {
	ID                       string    `json:"id"`
	SessionID                string    `json:"session_id"`
	Actor                    string    `json:"actor"`
	Path                     string    `json:"path"`
	Machine                  string    `json:"machine"`
	Model                    string    `json:"model"`
	InputTokens              int64     `json:"input_tokens"`
	OutputTokens             int64     `json:"output_tokens"`
	CacheReadInputTokens     int64     `json:"cache_read_input_tokens"`
	CacheCreationInputTokens int64     `json:"cache_creation_input_tokens"`
	Cost                     float64   `json:"cost"`
	Source                   string    `json:"source"`
	CreatedAt                time.Time `json:"created_at"`
}

type User struct {
	ID         string         `json:"id"`
	Handle     string         `json:"handle"`
	Role       string         `json:"role"`
	Active     bool           `json:"active"`
	SsoSubject sql.NullString `json:"sso_subject"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
