// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	// handle is COLLATE NOCASE at the schema level (see migration), so this
	// comparison is case-insensitive without needing an explicit COLLATE here.
	GetUserByHandle(ctx context.Context, handle string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserBySSOSubject(ctx context.Context, ssoSubject sql.NullString) (User, error)
	InsertUsageEventIgnoreDuplicate(ctx context.Context, arg InsertUsageEventIgnoreDuplicateParams) (int64, error)
	ListAPIKeysByOwner(ctx context.Context, userID string) ([]ApiKey, error)
	// Every active user, either role -- the assignee-picker's own source
	// (GET /api/bff/users), mirroring my-task's user.ts router exactly
	// (WHERE active = true ORDER BY handle, "humans and agents in one
	// list"). Inactive users are excluded so a picker never offers assigning
	// to someone who can no longer act.
	ListActiveUsers(ctx context.Context) ([]User, error)
	// I21 (_contract/INVARIANTS.md): the owner-facing key-listing endpoint
	// (GET /api/bff/keys) needs every role='agent' user's non-revoked keys,
	// not one user_id's own keys - the settings page's whole reason for
	// existing (GOAL.md's "Owner-facing key visibility" decision). A JOIN on
	// users from this file is a same-module reference (both api_keys and
	// users belong to the identity module per internal/dbquery/
	// tableisolation.go's TableOwnership) so it needs no ReadOnlyGrant - a
	// cross-module JOIN on a table owned elsewhere would.
	//
	// milestone-4 fix-round (handle-exposure): api_keys.* PLUS users.handle -
	// my-task's own src/app/(app)/settings/api-key-settings.tsx shows
	// `{k.handle}` on every row and its revoke dialog reads "Revoke
	// {handle}'s key?" (RevokeKeyButton) - the handle is the centre of that
	// whole interaction, not a nicety, so the owner-facing settings page
	// structurally cannot do its job without it. Still an explicit column
	// list, not a bare SELECT * against the join, for the same leak-prevention
	// reason as before - this query's own Go return type
	// (ListAllAgentAPIKeysRow) is scoped to this one query only; every other
	// query in this file keeps returning bare db.ApiKey, unaffected.
	ListAllAgentAPIKeys(ctx context.Context) ([]ListAllAgentAPIKeysRow, error)
	// story-1/ticket-14: every event whose created_at falls between the two
	// bound parameters below, range_start inclusive, range_end exclusive.
	// The raw rows behind the console's own read surface --
	// internal/domain/usage/summary.go's Aggregate does the group_by/window
	// math in Go, pure and unit-testable without sqlc/a real database; this
	// query's only job is the window filter itself.
	ListUsageEventsInWindow(ctx context.Context, arg ListUsageEventsInWindowParams) ([]UsageEvent, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	// The owner-facing revoke endpoint's own query (I21): session-gated to a
	// valid owner by the handler above this layer, but not scoped to any
	// particular user_id here - the owner may revoke any agent's key, and
	// there is structurally no api_keys row whose user_id ever belongs to a
	// role='owner' user (I2, cmd/issue-key only ever issues to role='agent'),
	// so no explicit role filter is needed for this to mean exactly "any
	// agent's key".
	RevokeAPIKeyByID(ctx context.Context, arg RevokeAPIKeyByIDParams) (ApiKey, error)
}

var _ Querier = (*Queries)(nil)
