// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	// handle is COLLATE NOCASE at the schema level (see migration), so this
	// comparison is case-insensitive without needing an explicit COLLATE here.
	GetUserByHandle(ctx context.Context, handle string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserBySSOSubject(ctx context.Context, ssoSubject sql.NullString) (User, error)
	// story-2/ticket-8 adds scan_root (the raw, resolved scan-root path the
	// reporting transcript file was found under -- distinct from `path`,
	// which is git-rooted from touched files).
	InsertUsageEventIgnoreDuplicate(ctx context.Context, arg InsertUsageEventIgnoreDuplicateParams) (int64, error)
	ListAPIKeysByOwner(ctx context.Context, userID string) ([]ApiKey, error)
	// Every active user, either role -- the assignee-picker's own source
	// (GET /api/bff/users), mirroring my-task's user.ts router exactly
	// (WHERE active = true ORDER BY handle, "humans and agents in one
	// list"). Inactive users are excluded so a picker never offers assigning
	// to someone who can no longer act.
	ListActiveUsers(ctx context.Context) ([]User, error)
	// I21 (_contract/INVARIANTS.md): the owner-facing key-listing endpoint
	// (GET /api/bff/keys) needs every role='agent' user's non-revoked keys,
	// not one user_id's own keys - the settings page's whole reason for
	// existing (GOAL.md's "Owner-facing key visibility" decision). A JOIN on
	// users from this file is a same-module reference (both api_keys and
	// users belong to the identity module per internal/dbquery/
	// tableisolation.go's TableOwnership) so it needs no ReadOnlyGrant - a
	// cross-module JOIN on a table owned elsewhere would.
	//
	// milestone-4 fix-round (handle-exposure): api_keys.* PLUS users.handle -
	// my-task's own src/app/(app)/settings/api-key-settings.tsx shows
	// `{k.handle}` on every row and its revoke dialog reads "Revoke
	// {handle}'s key?" (RevokeKeyButton) - the handle is the centre of that
	// whole interaction, not a nicety, so the owner-facing settings page
	// structurally cannot do its job without it. Still an explicit column
	// list, not a bare SELECT * against the join, for the same leak-prevention
	// reason as before - this query's own Go return type
	// (ListAllAgentAPIKeysRow) is scoped to this one query only; every other
	// query in this file keeps returning bare db.ApiKey, unaffected.
	ListAllAgentAPIKeys(ctx context.Context) ([]ListAllAgentAPIKeysRow, error)
	// Every known machine's install_id -> hostname mapping -- the "By
	// machine" breakdown's own label lookup (internal/domain/usage/
	// service.go's Summary, when group_by=machine substitutes each
	// breakdown row's raw install_id key for machines.hostname). The join
	// against usage_events.machine happens in Go over this result
	// (Service.Summary), not as a SQL JOIN here: Aggregate (summary.go) is
	// the existing pure function that already builds the breakdown keyed by
	// the raw install_id, so a hostname-substitution pass over its output
	// reuses that logic instead of re-deriving group_by/window aggregation
	// in SQL.
	ListMachines(ctx context.Context) ([]ListMachinesRow, error)
	// story-2/ticket-9: every registered scan_roots row across every
	// reporting install -- GET /api/bff/usage/scan-roots' own read path
	// (internal/domain/usage/service.go's Service.ScanRoots), populating the
	// console's future scan-root filter dropdown (ticket 11). No window
	// filter, no group_by -- this table is not usage_events, it's a small
	// upserted label table (mirrors ListMachines in machines.sql). The
	// install_id -> hostname join happens in Go over this result
	// (Service.ScanRoots, reusing the existing MachineHostnames query), not
	// as a SQL JOIN here -- same reasoning ListMachines' own doc comment
	// gives: reuse the pure aggregation/substitution logic that already
	// exists rather than re-deriving a join in SQL.
	ListScanRoots(ctx context.Context) ([]ListScanRootsRow, error)
	// story-1/ticket-14: every event whose created_at falls between the two
	// bound parameters below, range_start inclusive, range_end exclusive.
	// The raw rows behind the console's own read surface --
	// internal/domain/usage/summary.go's Aggregate does the group_by/window
	// math in Go, pure and unit-testable without sqlc/a real database; this
	// query's own job is the window/machine/scan_root filters.
	//
	// story-2/ticket-10 adds two optional filters, AND-composed with the
	// window bound and with each other: machine (the raw install_id) and
	// the scan_root pair (scan_root_install_id + scan_root_path together --
	// internal/domain/usage/repo.go decomposes the wire's own
	// <install_id>:<scan_root_path> composite into these two arguments
	// before this query ever runs, same machine-prefix convention ticket 7
	// established for group_by=path, contract's API surface section). Each
	// narg is NULL when its own filter was not requested --
	// "sqlc.narg(x) IS NULL OR column = sqlc.narg(x)" is the standard
	// optional-filter idiom, so one query text covers "no filter"/"one
	// filter"/"both filters" without a query-builder assembling different
	// SQL per case.
	ListUsageEventsInWindow(ctx context.Context, arg ListUsageEventsInWindowParams) ([]ListUsageEventsInWindowRow, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	// The owner-facing revoke endpoint's own query (I21): session-gated to a
	// valid owner by the handler above this layer, but not scoped to any
	// particular user_id here - the owner may revoke any agent's key, and
	// there is structurally no api_keys row whose user_id ever belongs to a
	// role='owner' user (I2, cmd/issue-key only ever issues to role='agent'),
	// so no explicit role filter is needed for this to mean exactly "any
	// agent's key".
	RevokeAPIKeyByID(ctx context.Context, arg RevokeAPIKeyByIDParams) (ApiKey, error)
	// story-1/ticket-18: the reporting collector's own (install_id, hostname)
	// pair, refreshed on every ingestion batch
	// (internal/domain/usage/service.go's UpsertMachine, called from
	// internal/transport/publicapi/usage_handler.go's
	// IngestUsageEventsBatch) so a renamed machine's console label catches up
	// rather than staying stuck on whatever hostname it was first seen with
	// (contract's Data model: `machines`). INSERT OR REPLACE, not
	// usage_events.sql's own INSERT OR IGNORE -- that table's row is meant
	// to change on every call (the opposite of usage_events' write-once
	// idempotency), and REPLACE gives that for free on a install_id conflict
	// since every column is supplied on every call (no partial-update case
	// this query ever needs). Deliberately not
	// "ON CONFLICT(install_id) DO UPDATE SET ..." -- that form's own
	// "DO UPDATE SET" false-positives internal/dbquery/tableisolation.go's
	// table scanner (it reads the SET clause's target list as if it named a
	// table called "set"; see that file's own doc comment on why its scanner
	// deliberately doesn't try to handle every SQL form rather than widen
	// itself further). INSERT OR REPLACE has no such clause and sidesteps
	// the false positive entirely, while remaining functionally equivalent
	// for this query's own all-columns-every-time shape.
	//
	// Note: this file must stay plain ASCII -- bin/sqlc v1.31.1 corrupts its
	// own star-expansion byte offsets on any non-ASCII byte in a
	// db/queries/*.sql file (internal/db_queries_ascii_test.go's own doc
	// comment has the full history). No em dashes, no Thai, no "section" /
	// other non-ASCII punctuation in this file.
	UpsertMachine(ctx context.Context, arg UpsertMachineParams) error
	// story-2/ticket-8: the reporting collector's own (install_id,
	// scan_root_path) pair, refreshed on every ingestion batch
	// (internal/domain/usage/service.go's UpsertScanRoots, called from
	// internal/transport/publicapi/usage_handler.go's
	// IngestUsageEventsBatch) so a renamed scan root's console label catches
	// up rather than staying stuck on whatever name it was first seen with
	// (contract's Data model: `scan_roots`). INSERT OR REPLACE, same idiom
	// machines.sql already uses -- not "ON CONFLICT(...) DO UPDATE SET ...",
	// which false-positives internal/dbquery/tableisolation.go's table
	// scanner (it reads the SET clause's target list as if it named a table
	// called "set"; see machines.sql's own header for the full explanation).
	// INSERT OR REPLACE has no such clause and remains functionally
	// equivalent here since every column is supplied on every call.
	//
	// Note: this file must stay plain ASCII -- bin/sqlc v1.31.1 corrupts its
	// own star-expansion byte offsets on any non-ASCII byte in a
	// db/queries/*.sql file (internal/db_queries_ascii_test.go's own doc
	// comment has the full history). No em dashes, no Thai, no "section" /
	// other non-ASCII punctuation in this file.
	UpsertScanRoot(ctx context.Context, arg UpsertScanRootParams) error
}

var _ Querier = (*Queries)(nil)
