// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_roots.sql

package db

import (
	"context"
	"time"
)

const upsertScanRoot = `-- name: UpsertScanRoot :exec
INSERT OR REPLACE INTO scan_roots (install_id, scan_root_path, name, source_type, last_seen_at)
VALUES (?, ?, ?, ?, ?)
`

type UpsertScanRootParams struct {
	InstallID    string    `json:"install_id"`
	ScanRootPath string    `json:"scan_root_path"`
	Name         string    `json:"name"`
	SourceType   string    `json:"source_type"`
	LastSeenAt   time.Time `json:"last_seen_at"`
}

// story-2/ticket-8: the reporting collector's own (install_id,
// scan_root_path) pair, refreshed on every ingestion batch
// (internal/domain/usage/service.go's UpsertScanRoots, called from
// internal/transport/publicapi/usage_handler.go's
// IngestUsageEventsBatch) so a renamed scan root's console label catches
// up rather than staying stuck on whatever name it was first seen with
// (contract's Data model: `scan_roots`). INSERT OR REPLACE, same idiom
// machines.sql already uses -- not "ON CONFLICT(...) DO UPDATE SET ...",
// which false-positives internal/dbquery/tableisolation.go's table
// scanner (it reads the SET clause's target list as if it named a table
// called "set"; see machines.sql's own header for the full explanation).
// INSERT OR REPLACE has no such clause and remains functionally
// equivalent here since every column is supplied on every call.
//
// Note: this file must stay plain ASCII -- bin/sqlc v1.31.1 corrupts its
// own star-expansion byte offsets on any non-ASCII byte in a
// db/queries/*.sql file (internal/db_queries_ascii_test.go's own doc
// comment has the full history). No em dashes, no Thai, no "section" /
// other non-ASCII punctuation in this file.
func (q *Queries) UpsertScanRoot(ctx context.Context, arg UpsertScanRootParams) error {
	_, err := q.db.ExecContext(ctx, upsertScanRoot,
		arg.InstallID,
		arg.ScanRootPath,
		arg.Name,
		arg.SourceType,
		arg.LastSeenAt,
	)
	return err
}
