// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_events.sql

package db

import (
	"context"
	"time"
)

const insertUsageEventIgnoreDuplicate = `-- name: InsertUsageEventIgnoreDuplicate :execrows
INSERT OR IGNORE INTO usage_events (id, session_id, actor, path, machine, model, input_tokens, output_tokens, cache_read_input_tokens, cache_creation_input_tokens, cost, source, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUsageEventIgnoreDuplicateParams struct {
	ID                       string    `json:"id"`
	SessionID                string    `json:"session_id"`
	Actor                    string    `json:"actor"`
	Path                     string    `json:"path"`
	Machine                  string    `json:"machine"`
	Model                    string    `json:"model"`
	InputTokens              int64     `json:"input_tokens"`
	OutputTokens             int64     `json:"output_tokens"`
	CacheReadInputTokens     int64     `json:"cache_read_input_tokens"`
	CacheCreationInputTokens int64     `json:"cache_creation_input_tokens"`
	Cost                     float64   `json:"cost"`
	Source                   string    `json:"source"`
	CreatedAt                time.Time `json:"created_at"`
}

func (q *Queries) InsertUsageEventIgnoreDuplicate(ctx context.Context, arg InsertUsageEventIgnoreDuplicateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertUsageEventIgnoreDuplicate,
		arg.ID,
		arg.SessionID,
		arg.Actor,
		arg.Path,
		arg.Machine,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadInputTokens,
		arg.CacheCreationInputTokens,
		arg.Cost,
		arg.Source,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
